import { createContact, createSpecial, createSupply, createTrade, createWorkItem, createMaterialEntry, timestamp, type ContactItem, type DailyReportV3, type MaterialEntry, type SpecialItem, type SupplyType, type TradeSection } from '../domain/daily';
import { localToday } from '../format/date-format';
import { saveDailyDraft } from '../data/daily-repository';
import { validateTrade } from './daily-validator';
import { duplicateVendorTradeIds } from './daily-output-model';

export type DailySaveState = 'saving' | 'saved' | 'error';
export interface TradeDeleteUndo { trade: TradeSection; originalIndex: number; connectedMaterialIds: string[]; }
export type DailyDeleteUndo = TradeDeleteUndo | { kind: 'material'; entry: MaterialEntry; originalIndex: number } | { kind: 'contact'; item: ContactItem; originalIndex: number } | { kind: 'special'; item: SpecialItem; originalIndex: number };
export interface MaterialConnectionUndo { materialId: string; tradeId: string; }

export class DailyController {
  report: DailyReportV3; expandedId: string | null = null; private timer?: number;
  constructor(report?: DailyReportV3, private readonly onSaveState?: (state: DailySaveState) => void) { const now = timestamp(); this.report = { id: 'current', date: localToday(), siteId: null, siteNameSnapshot: '', activeTab: 'engineering', tradeSections: [], standaloneMaterialEntries: [], supplies: [], contacts: [], specialItems: [], createdAt: now, updatedAt: now, ...report }; this.report.siteId ??= null; this.report.supplies ??= []; this.report.standaloneMaterialEntries ??= []; this.report.tradeSections.forEach((trade) => trade.materialEntries ??= []); this.report.contacts ??= []; this.report.specialItems ??= []; this.normalizeMaterialConnections(); }
  update(mutator: () => void): void { mutator(); this.report.updatedAt = timestamp(); this.onSaveState?.('saving'); window.clearTimeout(this.timer); this.timer = window.setTimeout(() => { void this.flush().catch(() => undefined); }, 600); }
  async flush(): Promise<void> { window.clearTimeout(this.timer); this.onSaveState?.('saving'); try { await saveDailyDraft(this.report); this.onSaveState?.('saved'); } catch (error) { this.onSaveState?.('error'); throw error; } }
  switchTab(tab: DailyReportV3['activeTab']): void { if (this.report.activeTab === tab) return; this.update(() => { if (this.report.activeTab === 'engineering') this.expandedId = null; this.report.activeTab = tab; }); }
  trade(id: string): TradeSection | undefined { return this.report.tradeSections.find((item) => item.id === id); }
  findDuplicate(tradeTypeId: string | null, tradeName: string, vendorId: string | null, vendorName: string, exceptId?: string): TradeSection | undefined { const normalizedTrade = tradeName.trim().toLocaleLowerCase(); const normalizedVendor = vendorName.trim().toLocaleLowerCase(); return this.report.tradeSections.find((item) => { const sameTrade = tradeTypeId && item.tradeTypeId ? item.tradeTypeId === tradeTypeId : !tradeTypeId && !item.tradeTypeId ? item.tradeNameSnapshot.trim().toLocaleLowerCase() === normalizedTrade : false; const sameVendor = vendorId && item.vendorId ? item.vendorId === vendorId : !vendorId && !item.vendorId ? item.vendorNameSnapshot.trim().toLocaleLowerCase() === normalizedVendor : false; return item.id !== exceptId && sameTrade && sameVendor; }); }
  addTrade(name: string, vendorName = '', tradeTypeId: string | null = null, vendorId: string | null = null): TradeSection | undefined { if (!name.trim()) return undefined; const existing = this.findDuplicate(tradeTypeId, name, vendorId, vendorName); if (existing) { this.expandedId = existing.id; return existing; } const section = createTrade(name, vendorName, this.report.tradeSections.length, tradeTypeId, vendorId); this.update(() => this.report.tradeSections.push(section)); this.expandedId = section.id; return section; }
  changeVendor(id: string, vendorName: string, vendorId: string | null = null): TradeSection | undefined { const trade = this.trade(id); if (!trade || !vendorName.trim()) return undefined; const existing = this.findDuplicate(trade.tradeTypeId, trade.tradeNameSnapshot, vendorId, vendorName, id); if (existing) { this.expandedId = existing.id; return existing; } this.updateTradeOutputData(id, (current) => { current.vendorId = vendorId; current.vendorNameSnapshot = vendorName.trim(); }); return undefined; }
  addWorkItem(tradeId: string): void { const trade = this.trade(tradeId); if (trade) this.updateTradeOutputData(tradeId, (current) => current.workItems.push(createWorkItem(current.workItems.length))); }
  addStandaloneMaterial(entryType: 'normal' | 'independent' = 'normal'): void { this.update(() => this.report.standaloneMaterialEntries.push(createMaterialEntry(this.report.standaloneMaterialEntries.length, entryType))); }
  private normalizeMaterialConnections(): void { const trades = new Set(this.report.tradeSections.map((trade) => trade.id)); this.report.standaloneMaterialEntries.forEach((entry) => { entry.entryType ??= 'normal'; if (entry.entryType !== 'independent' || !entry.connectedTradeSectionId || !trades.has(entry.connectedTradeSectionId)) entry.connectedTradeSectionId = null; }); }
  private markDraft(tradeId: string | null | undefined): void { const trade = tradeId ? this.trade(tradeId) : undefined; if (trade) trade.status = 'draft'; }
  updateTradeOutputData(tradeId: string, mutator: (trade: TradeSection) => void): boolean { const trade = this.trade(tradeId); if (!trade) return false; const before = JSON.stringify(trade); mutator(trade); if (before === JSON.stringify(trade)) return false; this.update(() => this.markDraft(tradeId)); return true; }
  connectMaterial(tradeId: string, materialId: string): { previousTradeId: string | null; targetTradeId: string } | undefined { const entry = this.materialEntry(materialId); const target = this.trade(tradeId); if (!entry || !target || entry.entryType !== 'independent') return undefined; const previousTradeId = entry.connectedTradeSectionId ?? null; if (previousTradeId === tradeId) return undefined; this.update(() => { entry.connectedTradeSectionId = tradeId; this.markDraft(previousTradeId); this.markDraft(tradeId); }); return { previousTradeId, targetTradeId: tradeId }; }
  disconnectMaterial(materialId: string): MaterialConnectionUndo | undefined { const entry = this.materialEntry(materialId); const tradeId = entry?.entryType === 'independent' ? entry.connectedTradeSectionId : null; if (!entry || !tradeId) return undefined; this.update(() => { entry.connectedTradeSectionId = null; this.markDraft(tradeId); }); return { materialId, tradeId }; }
  undoDisconnectMaterial(undo: MaterialConnectionUndo): boolean { const entry = this.materialEntry(undo.materialId); if (!entry || entry.entryType !== 'independent' || entry.connectedTradeSectionId || !this.trade(undo.tradeId)) return false; this.update(() => { entry.connectedTradeSectionId = undo.tradeId; this.markDraft(undo.tradeId); }); return true; }
  convertMaterialType(materialId: string): MaterialConnectionUndo | undefined { const entry = this.materialEntry(materialId); if (!entry) return undefined; const undo = entry.entryType === 'independent' && entry.connectedTradeSectionId ? { materialId, tradeId: entry.connectedTradeSectionId } : undefined; this.update(() => { entry.entryType = entry.entryType === 'normal' ? 'independent' : 'normal'; if (entry.entryType === 'normal') { entry.connectedTradeSectionId = null; this.markDraft(undo?.tradeId); } }); return undo; }
  connectStandaloneMaterial(tradeId: string, materialId: string): void { this.connectMaterial(tradeId, materialId); }
  disconnectStandaloneMaterial(materialId: string): void { this.disconnectMaterial(materialId); }
  materialEntry(materialId: string): MaterialEntry | undefined { return this.report.standaloneMaterialEntries.find((item) => item.id === materialId); }
  linkedMaterialEntries(tradeId: string): MaterialEntry[] { return this.report.standaloneMaterialEntries.filter((item) => item.entryType === 'independent' && item.connectedTradeSectionId === tradeId); }
  deleteMaterial(materialId: string): boolean { const entry = this.materialEntry(materialId); if (!entry) return false; const source = entry.entryType === 'independent' ? '獨立進料' : '普通進料'; if (!window.confirm(`確定刪除這筆進料？\n\n類型：${source}\n材料：${entry.itemName || entry.materialTypeSnapshot}\n供應商：${entry.supplierNameSnapshot}\n數量：${entry.quantity}${entry.unit}`)) return false; this.update(() => { this.report.standaloneMaterialEntries = this.report.standaloneMaterialEntries.filter((item) => item.id !== materialId); this.report.standaloneMaterialEntries.forEach((item, index) => item.sortOrder = index); }); return true; }
  deleteMaterialForUndo(id: string): DailyDeleteUndo | undefined { const entry = this.materialEntry(id); if (!entry) return undefined; const undo: DailyDeleteUndo = { kind: 'material', entry: structuredClone(entry), originalIndex: this.report.standaloneMaterialEntries.findIndex((item) => item.id === id) }; this.update(() => { this.report.standaloneMaterialEntries = this.report.standaloneMaterialEntries.filter((item) => item.id !== id); this.report.standaloneMaterialEntries.forEach((item, index) => item.sortOrder = index); }); return undo; }
  deleteContactForUndo(id: string): DailyDeleteUndo | undefined { const item = this.report.contacts.find((row) => row.id === id); if (!item) return undefined; const undo: DailyDeleteUndo = { kind: 'contact', item: structuredClone(item), originalIndex: this.report.contacts.findIndex((row) => row.id === id) }; this.update(() => { this.report.contacts = this.report.contacts.filter((row) => row.id !== id); this.report.contacts.forEach((row, index) => row.sortOrder = index); }); return undo; }
  deleteSpecialForUndo(id: string): DailyDeleteUndo | undefined { const item = this.report.specialItems.find((row) => row.id === id); if (!item) return undefined; const undo: DailyDeleteUndo = { kind: 'special', item: structuredClone(item), originalIndex: this.report.specialItems.findIndex((row) => row.id === id) }; this.update(() => { this.report.specialItems = this.report.specialItems.filter((row) => row.id !== id); this.report.specialItems.forEach((row, index) => row.sortOrder = index); }); return undo; }
  restoreDeletedItem(undo: DailyDeleteUndo): { skipped: number } { if ('trade' in undo) return this.restoreDeletedTrade(undo); this.update(() => { if (undo.kind === 'material') { if (this.materialEntry(undo.entry.id)) return; const entry = structuredClone(undo.entry); if (entry.connectedTradeSectionId && !this.trade(entry.connectedTradeSectionId)) entry.connectedTradeSectionId = null; this.report.standaloneMaterialEntries.splice(Math.max(0, Math.min(undo.originalIndex, this.report.standaloneMaterialEntries.length)), 0, entry); this.report.standaloneMaterialEntries.forEach((row, index) => row.sortOrder = index); } else if (undo.kind === 'contact') { if (this.report.contacts.some((row) => row.id === undo.item.id)) return; this.report.contacts.splice(Math.max(0, Math.min(undo.originalIndex, this.report.contacts.length)), 0, structuredClone(undo.item)); this.report.contacts.forEach((row, index) => row.sortOrder = index); } else { if (this.report.specialItems.some((row) => row.id === undo.item.id)) return; this.report.specialItems.splice(Math.max(0, Math.min(undo.originalIndex, this.report.specialItems.length)), 0, structuredClone(undo.item)); this.report.specialItems.forEach((row, index) => row.sortOrder = index); } }); return { skipped: 0 }; }
  deleteWorkItem(tradeId: string, workItemId: string): boolean { const trade = this.trade(tradeId); const work = trade?.workItems.find((item) => item.id === workItemId); if (!trade || !work) return false; const hasContent = Boolean(work.locationTextSnapshot.trim() || work.taskTextSnapshot.trim() || work.note.trim() || work.startFloorRaw || work.endFloorRaw); if (hasContent && !window.confirm('確定刪除此工項？刪除後無法復原。')) return false; this.updateTradeOutputData(tradeId, (current) => { current.workItems = current.workItems.filter((item) => item.id !== workItemId); current.workItems.forEach((item, index) => item.sortOrder = index); }); return true; }
  deleteTrade(id: string): boolean { const trade = this.trade(id); if (!trade) return false; const hasContent = Boolean(trade.workerCount || trade.workItems.length || this.linkedMaterialEntries(id).length); if (hasContent && !window.confirm(`確定刪除「${trade.tradeNameSnapshot}｜${trade.vendorNameSnapshot}」？\n\n施工資料會刪除；已連接的獨立進料會保留並自動解除連接。`)) return false; return Boolean(this.deleteTradeForUndo(id)); }
  deleteTradeForUndo(id: string): TradeDeleteUndo | undefined { const trade = this.trade(id); if (!trade) return undefined; const undo = { trade: structuredClone(trade), originalIndex: this.report.tradeSections.findIndex((item) => item.id === id), connectedMaterialIds: this.linkedMaterialEntries(id).map((entry) => entry.id) }; this.update(() => { this.report.standaloneMaterialEntries.forEach((entry) => { if (entry.connectedTradeSectionId === id) entry.connectedTradeSectionId = null; }); this.report.tradeSections = this.report.tradeSections.filter((item) => item.id !== id); this.report.tradeSections.forEach((item, index) => item.sortOrder = index); }); if (this.expandedId === id) this.expandedId = null; return undo; }
  restoreDeletedTrade(undo: TradeDeleteUndo): { reconnected: number; skipped: number } { let reconnected = 0; let skipped = 0; this.update(() => { if (this.trade(undo.trade.id)) return; const index = Math.max(0, Math.min(undo.originalIndex, this.report.tradeSections.length)); this.report.tradeSections.splice(index, 0, structuredClone(undo.trade)); this.report.tradeSections.forEach((item, order) => item.sortOrder = order); undo.connectedMaterialIds.forEach((materialId) => { const entry = this.materialEntry(materialId); if (!entry) { skipped += 1; return; } if (entry.connectedTradeSectionId === null || entry.connectedTradeSectionId === undefined) { entry.connectedTradeSectionId = undo.trade.id; reconnected += 1; } else skipped += 1; }); }); return { reconnected, skipped }; }
  reorderTrades(from: number, to: number): void { if (from === to || from < 0 || to < 0 || from >= this.report.tradeSections.length || to >= this.report.tradeSections.length) return; this.update(() => { const [section] = this.report.tradeSections.splice(from, 1); this.report.tradeSections.splice(to, 0, section); this.report.tradeSections.forEach((item, index) => item.sortOrder = index); }); }
  addSupply(type: SupplyType): void { this.update(() => this.report.supplies.push(createSupply(this.report.supplies.length, type))); }
  addContact(): void { this.update(() => this.report.contacts.push(createContact(this.report.contacts.length))); }
  addSpecial(): void { this.update(() => this.report.specialItems.push(createSpecial(this.report.specialItems.length))); }
  complete(tradeId: string): string[] { const trade = this.trade(tradeId); if (!trade) return []; const issues = validateTrade(trade, this.linkedMaterialEntries(tradeId)); if (duplicateVendorTradeIds(this.report).has(tradeId)) issues.push({ field: 'vendor', message: '同一工種不可有重複廠商施工卡。' }); if (!issues.length) this.update(() => { trade.status = 'complete'; this.expandedId = null; }); return issues.map((item) => item.message); }
  toggle(tradeId: string): void { const trade = this.trade(tradeId); if (!trade) return; this.expandedId = this.expandedId === tradeId ? null : tradeId; }
}
