export type TradeStatus = 'draft' | 'complete';
export interface WorkItem { id: string; startFloorRaw: string; startFloorNormalized: string | null; endFloorRaw: string; endFloorNormalized: string | null; locationId: string | null; locationTextSnapshot: string; taskId: string | null; taskTextSnapshot: string; note: string; sortOrder: number; createdAt: string; updatedAt: string; }
export type MaterialEntryType = 'normal' | 'independent';
export interface MaterialEntry { id: string; entryType?: MaterialEntryType; connectedTradeSectionId?: string | null; materialTypeId: string | null; materialTypeSnapshot: string; itemName: string; supplierId: string | null; supplierNameSnapshot: string; quantity: string; unit: string; specification: string; note: string; sortOrder: number; createdAt: string; updatedAt: string; }
export interface TradeSection { id: string; tradeTypeId: string | null; tradeNameSnapshot: string; vendorId: string | null; vendorNameSnapshot: string; workerCount: string; workItems: WorkItem[]; materialEntries: MaterialEntry[]; status: TradeStatus; sortOrder: number; createdAt: string; updatedAt: string; }
export type SupplyType = 'concrete' | 'clsm' | 'rebar' | 'other';
export interface SupplyItem { id: string; type: SupplyType; name: string; strength: string; quantity: string; unit: string; sortOrder: number; createdAt: string; updatedAt: string; }
export interface ContactItem { id: string; tradeNameSnapshot: string; vendorNameSnapshot: string; plannedDate: string; content: string; sortOrder: number; createdAt: string; updatedAt: string; }
export interface SpecialItem { id: string; content: string; sortOrder: number; createdAt: string; updatedAt: string; }
export interface DailyReportV3 { id: 'current'; date: string; siteId: string | null; siteNameSnapshot: string; activeTab: 'engineering' | 'supplies' | 'contacts' | 'special'; tradeSections: TradeSection[]; standaloneMaterialEntries: MaterialEntry[]; supplies: SupplyItem[]; contacts: ContactItem[]; specialItems: SpecialItem[]; createdAt: string; updatedAt: string; }
export const timestamp = (): string => new Date().toISOString();
export const createWorkItem = (sortOrder: number): WorkItem => ({ id: crypto.randomUUID(), startFloorRaw: '', startFloorNormalized: null, endFloorRaw: '', endFloorNormalized: null, locationId: null, locationTextSnapshot: '', taskId: null, taskTextSnapshot: '', note: '', sortOrder, createdAt: timestamp(), updatedAt: timestamp() });
export const createMaterialEntry = (sortOrder: number, entryType: MaterialEntryType = 'normal'): MaterialEntry => ({ id: crypto.randomUUID(), entryType, connectedTradeSectionId: null, materialTypeId: null, materialTypeSnapshot: '', itemName: '', supplierId: null, supplierNameSnapshot: '', quantity: '', unit: '', specification: '', note: '', sortOrder, createdAt: timestamp(), updatedAt: timestamp() });
export const createTrade = (name: string, vendorName: string, sortOrder: number, tradeTypeId: string | null = null, vendorId: string | null = null): TradeSection => ({ id: crypto.randomUUID(), tradeTypeId, tradeNameSnapshot: name.trim(), vendorId, vendorNameSnapshot: vendorName.trim(), workerCount: '', workItems: [], materialEntries: [], status: 'draft', sortOrder, createdAt: timestamp(), updatedAt: timestamp() });
export const createSupply = (sortOrder: number, type: SupplyType = 'concrete'): SupplyItem => ({ id: crypto.randomUUID(), type, name: '', strength: '', quantity: '', unit: '', sortOrder, createdAt: timestamp(), updatedAt: timestamp() });
export const createContact = (sortOrder: number): ContactItem => ({ id: crypto.randomUUID(), tradeNameSnapshot: '', vendorNameSnapshot: '', plannedDate: '', content: '', sortOrder, createdAt: timestamp(), updatedAt: timestamp() });
export const createSpecial = (sortOrder: number): SpecialItem => ({ id: crypto.randomUUID(), content: '', sortOrder, createdAt: timestamp(), updatedAt: timestamp() });
