import {build} from 'esbuild';
import {IDBFactory} from 'fake-indexeddb';
import {writeFile} from 'node:fs/promises';
globalThis.indexedDB=new IDBFactory();
globalThis.window=Object.assign(new EventTarget(),{setTimeout,clearTimeout});
globalThis.__auditScope={userId:'audit-user',siteId:'audit-site'};
globalThis.__auditRpc=async (name)=>({data:name==='pull_site_changes'?[]:{status:'duplicate',entity_id:'cloud',revision:2,remote_payload:{cloud:'unchanged'}},error:null});
const result=await build({stdin:{contents:`export {runSyncOnce} from './src/sync/engine.ts'; export {put,list} from './src/data/db.js';export {buildSyncOperation} from './src/sync/outbox.ts';`,resolveDir:process.cwd(),sourcefile:'audit-engine.ts'},bundle:true,platform:'node',format:'esm',write:false,preserveSymlinks:true,plugins:[{name:'isolated-audit',setup(b){
 b.onResolve({filter:/supabase-client$/},()=>({path:'client',namespace:'audit'}));
 b.onResolve({filter:/(^\.\/context$|sync\/context$)/},()=>({path:'context',namespace:'audit'}));
 b.onLoad({filter:/.*/,namespace:'audit'},a=>({contents:a.path==='client'?`export const getSupabaseClient=()=>({rpc:(...args)=>globalThis.__auditRpc(...args)}); export const sharedBackendEnabled=()=>true;`:`export const loadActiveSharedScope=async()=>globalThis.__auditScope;`,loader:'js'}));
}}],logLevel:'silent'});
await writeFile(new URL('./audit-engine.mjs',import.meta.url),result.outputFiles[0].text);
const m=await import('./audit-engine.mjs');const observations=[];
const operation=m.buildSyncOperation({...__auditScope,entity:'daily-draft',entityId:'cloud',baseRevision:1,payload:{date:'2026-10-04',local:'valuable edit'}});
await m.put('sync_outbox',operation);const summary=await m.runSyncOnce(__auditScope);
observations.push({id:'replayed-conflict-as-duplicate',summary,remaining:await m.list('sync_outbox'),backups:await m.list('sync_recovery_backups')});
const old={...operation,id:'old-conflict',status:'conflict'};await m.put('sync_outbox',old);await m.put('sync_conflicts',{id:old.id,...__auditScope,localPayload:old.payload});
const replacement=m.buildSyncOperation({...__auditScope,entity:'daily-patch',entityId:'cloud',baseRevision:2,payload:{reportDate:'2026-10-04',changes:[]}});replacement.resolvesConflictIds=[old.id];await m.put('sync_outbox',replacement);
globalThis.__auditRpc=async name=>({data:name==='pull_site_changes'?[]:{status:'applied',entity_id:'cloud',revision:3},error:null});
await m.runSyncOnce(__auditScope);observations.push({id:'resolution-discards-original',remaining:await m.list('sync_outbox'),conflicts:await m.list('sync_conflicts'),backups:await m.list('sync_recovery_backups')});
console.log(JSON.stringify(observations,null,2));await writeFile(new URL('./sync-reproductions.json',import.meta.url),JSON.stringify(observations,null,2));
