// Read-only audit harness: uses isolated in-memory IndexedDB; never accesses a browser profile.
import { build } from 'esbuild';
import { IDBFactory } from 'fake-indexeddb';
import { writeFile } from 'node:fs/promises';
const entry = `export * from './src/data/db.js';
export * from './src/domain/daily.ts';
export * from './src/data/daily-repository.ts';
export * from './src/daily/daily-controller.ts';
export * from './src/daily/daily-validator.ts';
export * from './src/sync/field-mutations.ts';
export * from './src/sync/conflict-review.ts';
export * from './src/account/account-view.ts';
export * from './src/water-level/controller.js';
export * from './src/water-level/calculator.js';
export * from './src/water-level/parser.js';`;
const bundled = await build({stdin:{contents:entry,resolveDir:process.cwd(),sourcefile:'audit-entry.ts'},bundle:true,platform:'node',format:'esm',write:false,preserveSymlinks:true,define:{'import.meta.env':'{}'},logLevel:'silent'});
await writeFile(new URL('./audit-modules.mjs',import.meta.url),bundled.outputFiles[0].text);
const m = await import('./audit-modules.mjs');
globalThis.indexedDB = new IDBFactory();
globalThis.window = Object.assign(new EventTarget(),{setTimeout,clearTimeout});
globalThis.document = {activeElement:null};
const result=[];
const record=(id,observed)=>{result.push({id,observed}); console.log(JSON.stringify({id,observed}));};
const req=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
// Versionchange oldVersion belongs to the event, not IDBOpenDBRequest.
const old = indexedDB.open('construction-daily-report',1);
old.onupgradeneeded=()=>{const d=old.result;d.createObjectStore('reports',{keyPath:'id'}).put({id:'legacy-report'});d.createObjectStore('drafts',{keyPath:'id'}).put({id:'current'});};
(await req(old)).close();
const upgraded=await m.openDatabase();upgraded.close();
record('migration',{legacy:(await m.list('reports')).length,migrated:(await m.list('daily_reports')).length,metadata:await m.list('migration_metadata')});
globalThis.indexedDB=new IDBFactory();
let report=m.createDailyDraft(null,'audit','2026-10-04');
const trade=m.createTrade('old','vendor',0);trade.workerCount='1';const work=m.createWorkItem(0);work.taskTextSnapshot='work';trade.workItems.push(work);report.tradeSections.push(trade);
await m.saveMemory('trades','old');const memory=(await m.listMemories('trades'))[0];report.tradeSections[0].tradeTypeId=memory.id;
await m.saveDailyDraft(report);await m.saveMemory('trades','new',undefined,memory.id);
record('rename-partition',{live:(await m.get('live_report_draft','current')).tradeSections[0].tradeNameSnapshot,reloaded:(await m.loadDailyDraft()).tradeSections[0].tradeNameSnapshot});
const controller=new m.DailyController(report);const before=structuredClone(controller.report);const undo=controller.removeWorkItemForUndo(trade.id,work.id);const removed=structuredClone(controller.report);undo();const restored=structuredClone(controller.report);await controller.flush();
record('undo-identities',{deletes:m.buildFieldMutations('daily',before,removed).filter(x=>x.op==='delete'),restores:m.buildFieldMutations('daily',removed,restored).filter(x=>x.op==='upsert')});
const root={innerHTML:'',querySelector:()=>null};const water=new m.WaterLevelController(root);await water.initialize();water.editing.battery='2.798';await water.refresh();record('water-refresh',{batteryAfterRefresh:water.editing.battery});
water.logs=[{id:'"><img src=x onerror="globalThis.__auditMarker=1">',measuredAt:'2026-10-04T12:00',readings:[],battery:''}];record('water-id-html',{containsInjectedTag:water.historyView().includes('<img src=x onerror=')});
const b={schemaVersion:1,points:[],logs:[{id:'old',measuredAt:'2026-09-01T00:00',readings:[]},{id:'recent',measuredAt:'2026-10-04T00:00',readings:[]}]};const a={...b,logs:[b.logs[1]]};record('water-prune-diff',m.buildFieldMutations('water',b,a));
const readings=m.recalculate([{id:'a',measuredAt:'2026-10-04T01:00',readings:[{pointId:'p',value:'10',change:null}]},{id:'b',measuredAt:'2026-10-04T02:00',readings:[{pointId:'p',value:'11',change:null}]}]);readings[1].readings[0].value='';record('water-empty-reading',m.recalculate(readings)[1].readings[0]);
const waterBefore={schemaVersion:1,points:[],logs:m.recalculate([{id:'a',measuredAt:'2026-10-04T01:00',readings:[{pointId:'p',value:'10',change:null}]},{id:'b',measuredAt:'2026-10-04T02:00',readings:[{pointId:'p',value:'11',change:null}]}])};const waterEdit=structuredClone(waterBefore);waterEdit.logs[0].readings[0].value='9';waterEdit.logs=m.recalculate(waterEdit.logs);const replayed=m.applyFieldMutations(waterBefore,m.buildFieldMutations('water',waterBefore,waterEdit));record('water-derived-sync',{localChange:waterEdit.logs[1].readings[0].change,remoteReplayChange:replayed.logs[1].readings[0].change});
record('quantity-half',m.validateMaterialEntry({...m.createMaterialEntry(0),materialTypeSnapshot:'x',itemName:'x',supplierNameSnapshot:'x',quantity:'0.5',unit:'t'}));
record('order-conflict',m.diffConflict({rows:[{id:'a'},{id:'b'}]},{rows:[{id:'b'},{id:'a'}]}));
record('water-invalid-import',m.parseWaterText('10/04-12點\nA井：1.2.3\n電池電量：invalid',2026));
const account={auth:{enabled:true,user:{id:'u'},session:null},sites:[],activeSiteId:null,pendingCount:0,requests:[],members:[],feedback:'',error:''};
record('account-name-attribute',{injected:m.renderAccountPage({...account,sites:[{id:'s',name:'x" onpointerenter="globalThis.__auditMarker=1;//',joinCode:'code',role:'viewer'}]}).includes('onpointerenter="globalThis.__auditMarker=1;')});
try { m.renderAccountPage({...account,conflicts:[{id:'c',operationId:'o',kind:'daily',entity:'daily-draft',createdAt:new Date().toISOString(),local:{},cloud:{x:1},diffs:m.diffConflict({}, {x:1})}]});record('conflict-missing-value',{threw:false}); } catch(e) { record('conflict-missing-value',{threw:true,error:e.message}); }
await writeFile(new URL('./reproductions.json',import.meta.url),JSON.stringify(result,null,2));
