import { formatWaterLogs } from './formatter.js';
import { parseWaterText } from './parser.js';
import { loadLogs, loadPoints, newLog, saveLog, deleteLog, savePoint, deletePoint } from './repository.js';
import { validateLog } from './calculator.js';

const escapeHtml = (value = '') => String(value).replace(/[&<>"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[char]));
export class WaterLevelController {
  constructor(root) { this.root = root; this.points = []; this.logs = []; this.editing = null; this.mode = 'entry'; }
  async initialize() { this.points = await loadPoints(); this.logs = await loadLogs(); this.editing = newLog(this.points); }
  async refresh() { this.points = await loadPoints(); this.logs = await loadLogs(); if (!this.editing || !this.editing.id) this.editing = newLog(this.points); this.render(); }
  preview() { return formatWaterLogs(this.logs); }
  render() { const log = this.editing; const errors = validateLog(log); this.root.innerHTML = `<section class="water-page"><div class="subtabs"><button type="button" data-water-view="entry" class="${this.mode === 'entry' ? 'active' : ''}">輸入水位</button><button type="button" data-water-view="history" class="${this.mode === 'history' ? 'active' : ''}">最近三天</button><button type="button" data-water-view="import" class="${this.mode === 'import' ? 'active' : ''}">貼上匯入</button></div>${this.mode === 'entry' ? this.entryView(log, errors) : this.mode === 'history' ? this.historyView() : this.importView()}</section>`; }
  renderSettings() { this.root.innerHTML = `<section class="water-page water-settings"><section class="form-card"><h2>井位管理</h2><p class="hint">刪除井位只影響後續輸入，既有歷史紀錄會保留名稱快照。</p>${this.pointsView()}</section></section>`; }
  entryView(log, errors) { return `<section class="form-card"><h2>${log.id ? '編輯量測紀錄' : '新增量測紀錄'}</h2><label>量測時間<input data-water-field="measuredAt" type="datetime-local" value="${escapeHtml(log.measuredAt)}"></label><label>電池電量（選填）<input data-water-field="battery" inputmode="decimal" value="${escapeHtml(log.battery)}" placeholder="例如 2.798"></label><div class="reading-list">${log.readings.length ? log.readings.map((reading, index) => `<label>${escapeHtml(reading.pointNameSnapshot)}<input data-water-reading="${index}" inputmode="decimal" value="${escapeHtml(reading.value)}" placeholder="空白表示無數據"></label>`).join('') : '<p class="empty">請先到「水位設定」新增量測井位。</p>'}</div>${errors.length ? `<ul class="issues">${errors.map((error) => `<li>${escapeHtml(error)}</li>`).join('')}</ul>` : ''}<div class="action-row"><button type="button" class="primary" data-water-action="save-log">儲存量測</button>${log.id ? '<button type="button" data-water-action="cancel-edit">取消編輯</button>' : ''}</div></section>`; }
  historyView() { return `<section class="history-list"><h2>最近三天量測</h2>${this.logs.length ? [...this.logs].reverse().map((log) => `<article><pre>${escapeHtml(formatWaterLogs([log]))}</pre><button type="button" data-water-action="edit-log" data-id="${log.id}">編輯</button><button type="button" class="danger-text" data-water-action="delete-log" data-id="${log.id}">刪除</button></article>`).join('') : '<p class="empty">尚無最近三天的水位紀錄。</p>'}</section>`; }
  importView() { return `<section class="form-card"><h2>貼上水位文字</h2><p class="hint">每筆量測以空白行分隔。格式：M/D-H點、井位：數值(下降/上升數值)、電池電量。</p><textarea id="water-import-text" rows="10" placeholder="7/29-16點\nA井：10.452(下降0.113)\n電池電量：2.798"></textarea><button type="button" class="primary" data-water-action="parse-import">解析並匯入</button><div id="import-result"></div></section>`; }
  pointsView() { return `<form id="point-form"><label>井位名稱<input name="name" required placeholder="例如 A井"></label><button type="submit" class="primary">新增井位</button></form><div class="point-list">${this.points.map((point) => `<article><strong>${escapeHtml(point.name)}</strong><button type="button" data-water-action="rename-point" data-id="${point.id}">改名</button><button type="button" class="danger-text" data-water-action="delete-point" data-id="${point.id}">刪除</button></article>`).join('') || '<p class="empty">尚未建立井位。</p>'}</div>`; }
  async handleInput(target) { if (target.dataset.waterField) this.editing[target.dataset.waterField] = target.value; if (target.dataset.waterReading) this.editing.readings[Number(target.dataset.waterReading)].value = target.value; }
  async handleAction(action, id) { if (action === 'save-log') { const errors = validateLog(this.editing); if (errors.length) return this.render(); await saveLog(this.editing); this.editing = newLog(await loadPoints()); await this.refresh(); } if (action === 'save-point') { await savePoint(String(id)); await this.refresh(); } if (action === 'cancel-edit') { this.editing = newLog(await loadPoints()); this.mode = 'entry'; this.render(); } if (action === 'edit-log') { this.editing = structuredClone(this.logs.find((log) => log.id === id)); this.mode = 'entry'; this.render(); } if (action === 'delete-log' && confirm('刪除後，後續下降量將重新計算。確定刪除？')) { await deleteLog(id); await this.refresh(); } if (action === 'delete-point' && confirm('刪除井位只影響後續輸入，不會刪除歷史讀值。確定刪除？')) { await deletePoint(id); await this.refresh(); } if (action === 'rename-point') { const point = this.points.find((item) => item.id === id); const name = prompt('新的井位名稱', point.name); if (name !== null) { await savePoint(name, id); await this.refresh(); } } if (action === 'parse-import') await this.importText(); }
  async importText() { const text = this.root.querySelector('#water-import-text').value; const parsed = parseWaterText(text); const result = this.root.querySelector('#import-result'); const messages = []; for (const segment of parsed) { if (!segment.ok) { messages.push(`略過：${segment.error}`); continue; } const pointMap = new Map(this.points.map((point) => [point.name, point])); for (const reading of segment.readings) { if (!pointMap.has(reading.pointNameSnapshot)) { const point = await savePoint(reading.pointNameSnapshot); this.points.push(point); pointMap.set(point.name, point); } reading.pointId = pointMap.get(reading.pointNameSnapshot).id; } const existing = this.logs.find((log) => log.measuredAt === segment.measuredAt); if (existing && !confirm(`${segment.measuredAt} 已有量測紀錄，是否覆蓋？`)) { messages.push(`${segment.measuredAt}：略過重複紀錄`); continue; } await saveLog({ id: existing?.id || '', measuredAt: segment.measuredAt, battery: segment.battery, readings: segment.readings }); messages.push(`${segment.measuredAt}：已匯入`); } await this.refresh(); this.mode = 'import'; this.render(); const next = this.root.querySelector('#import-result'); if (next) next.innerHTML = `<ul>${messages.map((message) => `<li>${escapeHtml(message)}</li>`).join('')}</ul>`; }
}
