import './styles.css';
import './daily/daily.css';
import './daily/debug-layout.css';
import './daily/dialog.css';
import { DailyController } from './daily/daily-controller';
import { formatDailyReport } from './daily/daily-formatter';
import { clearDebugLogs, confirmMemory, databaseSummary, deleteMemory, listMemories, listTemplates, loadDailyDraft, saveMemory, saveTemplate, type DailySettingsSection, type NamedMemory, type SpecialTemplate } from './data/daily-repository';
import { comparableFloor, normalizeFloor } from './daily/floor';
import type { DailyReportV3, TradeSection } from './domain/daily';

type AppRoute =
  | { module: 'daily'; page: 'main' }
  | { module: 'daily'; page: 'settings' }
  | { module: 'water-level'; page: 'main' }
  | { module: 'water-level'; page: 'settings' };
type WaterController = { initialize(): Promise<void>; render(): void; renderSettings(): void; handleInput(target: HTMLElement): Promise<void>; handleAction(action: string, id?: string): Promise<void>; preview(): string; mode: string };

const app = document.querySelector<HTMLDivElement>('#app')!;
let daily!: DailyController;
let water: WaterController | undefined;
let tradePickerOpen = false;
let dailyTrades: NamedMemory[] = []; let dailyVendors: NamedMemory[] = [];
let renderToken = 0;
let settingsSearchComposing = false;
const tradeDrag = { active: false, id: null as string | null, originalOrder: [] as string[], originalExpandedId: null as string | null, pointerId: null as number | null, offsetX: 0, offsetY: 0, activeDropSlotIndex: null as number | null, preview: null as HTMLElement | null, frame: null as number | null, clientX: 0, clientY: 0 };
const settingsState: { activeSection: DailySettingsSection; editingId: string | null; adding: boolean; dirty: boolean; selectedTradeTypeId: string | null; taskSearchKeyword: string } = { activeSection: 'sites', editingId: null, adding: false, dirty: false, selectedTradeTypeId: null, taskSearchKeyword: '' };
let settingsRows: NamedMemory[] = []; let settingsTrades: NamedMemory[] = []; let settingsTemplates: SpecialTemplate[] = []; let settingsDebug: Record<string, number> = {};
const escapeHtml = (value: string) => value.replace(/[&<>']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;' }[char]!));
const field = (label: string, name: string, value: string, type = 'text') => `<label>${label}<input data-daily-field="${name}" type="${type}" value="${escapeHtml(value)}"></label>`;
const tabs: Array<[DailyReportV3['activeTab'], string]> = [['engineering', '工程條目'], ['supplies', '進料'], ['contacts', '聯絡事項'], ['special', '特殊事項']];

function parseRoute(hash: string): AppRoute {
  const normalized = hash || '#daily';
  if (normalized === '#daily') return { module: 'daily', page: 'main' };
  if (normalized === '#daily/settings') return { module: 'daily', page: 'settings' };
  if (normalized === '#water-level') return { module: 'water-level', page: 'main' };
  if (normalized === '#water-level/settings') return { module: 'water-level', page: 'settings' };
  return { module: 'daily', page: 'main' };
}

function dailyTabs(): string { return `<section class="daily-tabs" role="tablist" aria-label="施工日報分類">${tabs.map(([id, label]) => `<button type="button" role="tab" data-daily-tab="${id}" aria-selected="${daily.report.activeTab === id}" class="${daily.report.activeTab === id ? 'active' : ''}">${label}</button>`).join('')}</section>`; }
function workItemView(trade: TradeSection, work: TradeSection['workItems'][number]): string {
  return `<div class="work-item" data-work="${work.id}"><div class="work-item-location-row" style="display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr) minmax(0,2fr);gap:.5rem;align-items:start"><input style="min-width:0;padding:.62rem .45rem" data-daily-field="startFloorRaw" aria-label="起始樓層" placeholder="起始" value="${escapeHtml(work.startFloorRaw)}"><input style="min-width:0;padding:.62rem .45rem" data-daily-field="endFloorRaw" aria-label="結束樓層" placeholder="結束" value="${escapeHtml(work.endFloorRaw)}"><input style="min-width:0;padding:.62rem .45rem" data-daily-field="locationTextSnapshot" aria-label="位置（選填）" placeholder="位置（選填）" value="${escapeHtml(work.locationTextSnapshot)}"></div>${field('工項', 'taskTextSnapshot', work.taskTextSnapshot)}<label>備註<textarea data-daily-field="note">${escapeHtml(work.note)}</textarea></label><div class="work-item-actions"><button type="button" class="danger-text work-item-delete" data-daily-action="delete-work-item" data-trade-id="${trade.id}" data-work-item-id="${work.id}">刪除工項</button></div></div>`;
}
function tradeCard(trade: TradeSection, index: number): string {
  const expanded = !tradeDrag.active && daily.expandedId === trade.id;
  const handle = `<button type="button" class="drag-handle" data-drag-trade="${trade.id}" aria-label="拖曳排序" style="cursor:grab;touch-action:none">☰</button>`;
  if (tradeDrag.active && tradeDrag.id === trade.id) return `<article class="trade-card" data-trade="${trade.id}" style="height:76px;border-style:dashed;background:transparent;pointer-events:none"></article>`;
  const sortableIndex = daily.report.tradeSections.filter((item) => item.id !== tradeDrag.id).findIndex((item) => item.id === trade.id); const indicator = tradeDrag.active && tradeDrag.activeDropSlotIndex === sortableIndex ? '<div class="trade-drop-indicator" style="height:4px;border-radius:2px;background:#df9c2e;margin:-.75rem 0 .55rem;pointer-events:none"></div>' : '';
  if (!expanded) return `${indicator}<article class="trade-card trade-card--${trade.status}" data-trade="${trade.id}" data-sortable-trade data-trade-index="${index}">${handle}<button type="button" class="trade-card__header" data-daily-action="toggle-trade" data-id="${trade.id}"><span>${escapeHtml(trade.tradeNameSnapshot)}｜${escapeHtml(trade.vendorNameSnapshot)}</span><span>${trade.status === 'complete' ? '▸ 已完成' : '⚠ 未完成'}</span></button></article>`;
  return `${indicator}<article class="trade-card trade-card--${trade.status}" data-trade="${trade.id}" data-sortable-trade data-trade-index="${index}"><header>${handle}<strong>${escapeHtml(trade.tradeNameSnapshot)}</strong><span>${trade.status === 'complete' ? '已完成' : '編輯中'}</span></header><section class="vendor-card">${field('廠商', 'vendorNameSnapshot', trade.vendorNameSnapshot)}${field('施工人數', 'workerCount', trade.workerCount, 'text')}${trade.workItems.map((work) => workItemView(trade, work)).join('') || '<p class="empty">尚無工項。</p>'}<button type="button" data-daily-action="add-work" data-trade-id="${trade.id}">＋ 新增工項</button></section><div class="action-row"><button type="button" data-daily-action="collapse">暫時收合</button><button type="button" class="danger-text" data-daily-action="delete-trade" data-id="${trade.id}">刪除工種</button>${trade.status === 'draft' ? `<button type="button" class="primary" data-daily-action="complete" data-id="${trade.id}">完成工種</button>` : ''}</div></article>`;
}
function activeTabContent(): string {
  if (daily.report.activeTab === 'engineering') { const trailing = tradeDrag.active && tradeDrag.activeDropSlotIndex === daily.report.tradeSections.filter((item) => item.id !== tradeDrag.id).length ? '<div class="trade-drop-indicator" style="height:4px;border-radius:2px;background:#df9c2e;margin:.55rem 0;pointer-events:none"></div>' : ''; return `<section class="trade-list">${daily.report.tradeSections.map(tradeCard).join('') || '<p class="empty">尚未新增工程條目。</p>'}${trailing}</section>`; }
  if (daily.report.activeTab === 'supplies') return `<section class="form-card"><h2>進料</h2><div class="quick-add"><button type="button" data-daily-action="add-supply" data-type="concrete">＋ 混凝土</button><button type="button" data-daily-action="add-supply" data-type="clsm">＋ CLSM</button><button type="button" data-daily-action="add-supply" data-type="rebar">＋ 鋼筋</button><button type="button" data-daily-action="add-supply" data-type="other">＋ 其他</button></div>${daily.report.supplies.map((item) => `<section class="entry" data-supply="${item.id}"><strong>${item.type}</strong>${field('數量', 'quantity', item.quantity)}<button type="button" class="danger-text" data-daily-action="delete-supply" data-id="${item.id}">刪除</button></section>`).join('') || '<p class="empty">尚未新增進料。</p>'}</section>`;
  if (daily.report.activeTab === 'contacts') return `<section class="form-card"><h2>聯絡事項</h2><button type="button" data-daily-action="add-contact">＋ 新增聯絡事項</button>${daily.report.contacts.map((item) => `<section class="entry" data-contact="${item.id}">${field('工種', 'tradeNameSnapshot', item.tradeNameSnapshot)}${field('廠商', 'vendorNameSnapshot', item.vendorNameSnapshot)}${field('預定日期', 'plannedDate', item.plannedDate, 'date')}<label>內容<textarea data-daily-field="content">${escapeHtml(item.content)}</textarea></label><button type="button" class="danger-text" data-daily-action="delete-contact" data-id="${item.id}">刪除</button></section>`).join('') || '<p class="empty">尚未新增聯絡事項。</p>'}</section>`;
  return `<section class="form-card"><h2>特殊事項</h2><button type="button" data-daily-action="add-special">＋ 新增特殊事項</button>${daily.report.specialItems.map((item) => `<section class="entry" data-special="${item.id}"><label>事項內容<textarea data-daily-field="content">${escapeHtml(item.content)}</textarea></label><button type="button" class="danger-text" data-daily-action="delete-special" data-id="${item.id}">刪除</button></section>`).join('') || '<p class="empty">尚未新增特殊事項。</p>'}</section>`;
}
function dailyView(): string {
  const completed = daily.report.tradeSections.filter((trade) => trade.status === 'complete'); const drafts = daily.report.tradeSections.filter((trade) => trade.status === 'draft');
  const picker = tradePickerOpen ? `<div class="dialog-backdrop"><form class="trade-picker" id="trade-picker-form"><h2>新增工種區塊</h2><label>工種<select name="tradeId" required autofocus><option value="">請選擇工種</option>${dailyTrades.map((item) => `<option value="${item.id}">${escapeHtml(item.name)}</option>`).join('')}</select></label><label>廠商<select name="vendorId" required><option value="">請選擇廠商</option>${dailyVendors.map((item) => `<option value="${item.id}" data-trade-type="${item.tradeTypeId ?? ''}">${escapeHtml(item.name)}</option>`).join('')}</select></label><p class="hint">請先至設定頁建立工種與其廠商；同一工種與廠商不可重複。</p><div class="action-row"><button type="button" data-daily-action="close-trade-picker">取消</button><button class="primary" type="submit">建立工種</button></div></form></div>` : '';
  return `<main class="app-shell"><header class="top app-header"><div><p class="eyebrow">FIELD NOTEBOOK · LOCAL ONLY</p><h1>施工日報</h1></div><a class="settings-button" href="#daily/settings" aria-label="開啟施工日報設定">⚙ 設定</a></header><nav class="top-tabs"><a class="active" href="#daily">施工日報</a><a href="#water-level">水位變化</a></nav><section class="basics">${field('日期', 'date', daily.report.date, 'date')}${field('工地', 'siteNameSnapshot', daily.report.siteNameSnapshot)}</section>${dailyTabs()}${activeTabContent()}${daily.report.activeTab === 'engineering' && !daily.expandedId ? '<button type="button" class="floating-add-trade" data-daily-action="add-trade">＋ 工種</button>' : ''}<aside class="preview bottom-preview"><p class="eyebrow">DAILY OUTPUT</p><strong>${daily.report.siteNameSnapshot || '尚未設定工地'}｜${daily.report.date}</strong><div class="preview-tags">${completed.map((trade) => `<button type="button" data-daily-action="toggle-trade" data-id="${trade.id}">${escapeHtml(trade.tradeNameSnapshot)}</button>`).join('')}</div>${drafts.length ? `<p>尚有 ${drafts.length} 個未完成工種未納入預覽。</p>` : ''}<pre>${escapeHtml(formatDailyReport(daily.report) || '完成工種後，這裡會顯示日報預覽。')}</pre><button type="button" class="primary" data-daily-action="copy" ${drafts.length ? 'disabled' : ''}>複製完整日報</button></aside>${picker}</main>`;
}
const sectionLabels: Array<[DailySettingsSection, string]> = [['sites', '工地管理'], ['trade-tasks', '工種與工項管理'], ['vendors', '廠商管理'], ['locations', '位置管理'], ['templates', '特殊事項模板'], ['backup', '備份與還原'], ['debug', '偵錯資訊']];
function settingsItems(): string {
  const section = settingsState.activeSection;
  if (section === 'backup') return `<section class="form-card"><h2>備份與還原</h2><p class="hint">完整備份與還原會在後續版本加入安全備份檔流程；目前資料不會因進入此頁而變更。</p></section>`;
  if (section === 'debug') return `<section class="form-card"><h2>偵錯資訊</h2><pre>${escapeHtml(JSON.stringify({ appVersion: '0.1.0', databaseVersion: 4, route: location.hash, draft: { date: daily.report.date, trades: daily.report.tradeSections.length }, serviceWorker: navigator.serviceWorker?.controller ? 'active' : 'not active', stores: settingsDebug }, null, 2))}</pre><div class="action-row"><button type="button" data-settings-action="copy-debug">複製偵錯資訊</button><button type="button" class="danger-text" data-settings-action="clear-debug">清除偵錯紀錄</button></div></section>`;
  if (section === 'trade-tasks') return tradeTasksSettings();
  const needsTrade = section === 'vendors'; const title = sectionLabels.find(([key]) => key === section)?.[1] ?? '';
  const rows = section === 'templates' ? settingsTemplates : settingsRows;
  const tradeSelect = needsTrade ? `<label>工種<select data-settings-field="trade"><option value="">請選擇工種</option>${settingsTrades.map((trade) => `<option value="${trade.id}" ${settingsState.selectedTradeTypeId === trade.id ? 'selected' : ''}>${escapeHtml(trade.name)}</option>`).join('')}</select></label>` : '';
  if (needsTrade && !settingsState.selectedTradeTypeId) return `<section class="form-card"><h2>${title}</h2>${tradeSelect}<p class="hint">請先選擇工種，才能查看與管理${section === 'vendors' ? '廠商' : '工項'}。</p></section>`;
  if (false) {
    const keyword = normalizeSearch(settingsState.taskSearchKeyword); const matched = settingsRows.filter((row) => !keyword || row.normalizedName.includes(keyword)); const candidates = matched.filter((row) => row.status === 'candidate'); const confirmed = matched.filter((row) => row.status !== 'candidate'); const action = keyword ? (matched.length ? '<button type="button" data-settings-action="clear-task-search">清除</button>' : '<button type="button" data-settings-action="add-task-from-search">立即新增工項</button>') : ''; const taskRows = (items: NamedMemory[], label: string) => `<section class="task-status-group"><h3>${label}</h3>${items.length ? items.map((row) => `<article class="settings-item"><strong>${escapeHtml(row.name)}</strong><div class="settings-item-actions">${row.status === 'candidate' ? `<button type="button" data-settings-action="confirm" data-id="${row.id}">確認</button>` : ''}<button type="button" data-settings-action="edit" data-id="${row.id}">編輯</button><button type="button" class="danger-text" data-settings-action="delete" data-id="${row.id}" data-name="${escapeHtml(row.name)}">刪除</button></div>${settingsState.editingId === row.id ? taskForm('edit', row.name) : ''}</article>`).join('') : '<p class="empty">沒有符合的工項。</p>'}</section>`; const add = settingsState.adding ? taskForm('add', settingsState.taskSearchKeyword) : '<button type="button" data-settings-action="add">＋ 新增工項</button>'; return `<section class="form-card"><h2>${title}</h2>${tradeSelect}<div class="task-search" style="display:grid;grid-template-columns:minmax(0,1fr) auto;gap:.5rem;align-items:center;margin:.8rem 0"><input data-settings-search="tasks" aria-label="搜尋工項關鍵字" placeholder="搜尋工項關鍵字" value="${escapeHtml(settingsState.taskSearchKeyword)}">${action}</div>${add}${!matched.length && keyword ? '<p class="empty">找不到符合的工項。</p>' : `${taskRows(candidates, '待確認')}${taskRows(confirmed, '已確認')}`}</section>`;
  }
  const itemRows = rows.map((row) => { const id = row.id; const text = section === 'templates' ? (row as SpecialTemplate).text : (row as NamedMemory).name; const editing = settingsState.editingId === id; return `<article class="settings-item"><strong>${escapeHtml(text)}</strong><div class="settings-item-actions">${section !== 'sites' && section !== 'trades' && section !== 'templates' && (row as NamedMemory).status === 'candidate' ? `<button type="button" data-settings-action="confirm" data-id="${id}">確認</button>` : ''}<button type="button" data-settings-action="edit" data-id="${id}">編輯</button><button type="button" class="danger-text" data-settings-action="delete" data-id="${id}" data-name="${escapeHtml(text)}">刪除</button></div>${editing ? `<form class="settings-edit-form" data-settings-form="edit"><label>名稱<input name="name" maxlength="${section === 'templates' ? 500 : 50}" value="${escapeHtml(text)}" autofocus></label><div class="action-row"><button class="primary" type="submit">儲存</button><button type="button" data-settings-action="cancel">取消</button></div></form>` : ''}</article>`; }).join('') || '<p class="empty">尚無設定資料。</p>';
  const add = settingsState.adding ? `<form class="settings-edit-form" data-settings-form="add"><label>${section === 'templates' ? '模板內容' : '名稱'}<input name="name" maxlength="${section === 'templates' ? 500 : 50}" autofocus></label><div class="action-row"><button class="primary" type="submit">儲存</button><button type="button" data-settings-action="cancel">取消</button></div></form>` : `<button type="button" data-settings-action="add">＋ 新增${title.replace('管理', '')}</button>`;
  return `<section class="form-card"><h2>${title}</h2>${tradeSelect}${add}<div class="settings-list">${itemRows}</div></section>`;
}
function tradeTasksSettings(): string {
  const expandedId = settingsState.selectedTradeTypeId; const keyword = normalizeSearch(settingsState.taskSearchKeyword); const tasks = settingsRows.filter((row) => !keyword || row.normalizedName.includes(keyword)); const candidates = tasks.filter((row) => row.status === 'candidate'); const confirmed = tasks.filter((row) => row.status !== 'candidate');
  const taskList = (items: NamedMemory[], title: string) => `<section class="task-status-group"><h3>${title}</h3>${items.length ? items.map((task) => `<article class="settings-item"><strong>${escapeHtml(task.name)}</strong><div class="settings-item-actions">${task.status === 'candidate' ? `<button type="button" data-settings-action="confirm" data-settings-kind="tasks" data-id="${task.id}">確認</button>` : ''}<button type="button" data-settings-action="edit-task" data-id="${task.id}">編輯</button><button type="button" class="danger-text" data-settings-action="delete" data-settings-kind="tasks" data-id="${task.id}" data-name="${escapeHtml(task.name)}">刪除</button></div>${settingsState.editingId === task.id ? taskForm('edit', task.name) : ''}</article>`).join('') : '<p class="empty">沒有符合的工項。</p>'}</section>`;
  const taskPanel = (trade: NamedMemory) => { if (expandedId !== trade.id) return ''; const taskAction = keyword ? (tasks.length ? '<button type="button" data-settings-action="clear-task-search">清除</button>' : '<button type="button" data-settings-action="add-task-from-search">立即新增工項</button>') : ''; const add = settingsState.adding ? taskForm('add', settingsState.taskSearchKeyword) : '<button type="button" data-settings-action="add-task">＋ 新增工項</button>'; return `<div class="trade-task-panel"><div class="task-search" style="display:grid;grid-template-columns:minmax(0,1fr) auto;gap:.5rem;align-items:center;margin:.8rem 0"><input data-settings-search="tasks" aria-label="搜尋此工種的工項" placeholder="搜尋此工種的工項" value="${escapeHtml(settingsState.taskSearchKeyword)}">${taskAction}</div>${add}${!tasks.length && keyword ? '<p class="empty">找不到符合的工項。</p>' : `${taskList(candidates, '待確認')}${taskList(confirmed, '已確認')}`}</div>`; };
  const trades = settingsTrades.map((trade) => `<article class="settings-item trade-task-item" data-trade-type-id="${trade.id}"><div class="trade-task-header"><button type="button" class="trade-toggle" data-settings-action="toggle-trade-tasks" data-trade-type-id="${trade.id}">${expandedId === trade.id ? '▾' : '▸'} ${escapeHtml(trade.name)}</button><div class="settings-item-actions"><button type="button" data-settings-action="edit-trade" data-id="${trade.id}">編輯</button><button type="button" class="danger-text" data-settings-action="delete" data-settings-kind="trades" data-id="${trade.id}" data-name="${escapeHtml(trade.name)}">刪除</button></div></div>${settingsState.editingId === trade.id ? tradeForm(trade.name) : ''}${taskPanel(trade)}</article>`).join('') || '<p class="empty">尚無工種。</p>';
  return `<section class="form-card"><h2>工種與工項管理</h2>${settingsState.adding && !expandedId ? tradeForm() : '<button type="button" data-settings-action="add-trade">＋ 新增工種</button>'}<div class="settings-list">${trades}</div></section>`;
}
function normalizeSearch(value: string): string { return value.trim().replace(/　/g, ' ').replace(/\s+/g, ' ').toLocaleLowerCase('en-US'); }
function tradeForm(value = ''): string { return `<form class="settings-edit-form" data-settings-form="trade"><label>工種名稱<input name="name" maxlength="50" value="${escapeHtml(value)}" autofocus></label><div class="action-row"><button class="primary" type="submit">儲存</button><button type="button" data-settings-action="cancel">取消</button></div></form>`; }
function taskForm(mode: 'add' | 'edit', value = ''): string { return `<form class="settings-edit-form" data-settings-form="${mode}"><label>工項名稱<input name="name" maxlength="50" value="${escapeHtml(value)}" autofocus></label><div class="action-row"><button class="primary" type="submit">儲存</button><button type="button" data-settings-action="cancel">取消</button></div></form>`; }
function dailySettingsView(): string { return `<main class="app-shell settings-page"><header class="top app-header"><div><p class="eyebrow">DAILY SETTINGS</p><h1>施工日報設定</h1></div><a class="settings-button" href="#daily">返回日報</a></header><nav class="top-tabs"><a class="active" href="#daily">施工日報</a><a href="#water-level">水位變化</a></nav><section class="settings-section-grid">${sectionLabels.map(([key, label]) => `<button type="button" data-settings-section="${key}" class="${settingsState.activeSection === key ? 'active' : ''}">${label}</button>`).join('')}</section>${settingsItems()}<p class="hint">設定與施工日報共用同一份草稿；既有日報快照不會因管理操作而被改寫。</p></main>`; }
function waterShell(settings: boolean): string { return `<main class="app-shell"><header class="top app-header"><div><p class="eyebrow">${settings ? 'WATER LEVEL SETTINGS' : 'WATER LEVEL'}</p><h1>${settings ? '水位設定' : '水位變化'}</h1></div><a class="settings-button" href="${settings ? '#water-level' : '#water-level/settings'}">${settings ? '返回水位' : '⚙ 設定'}</a></header><nav class="top-tabs"><a href="#daily">施工日報</a><a class="active" href="#water-level">水位變化</a></nav><div id="water-root"></div>${settings ? '' : '<aside class="preview bottom-preview"><p class="eyebrow">WATER OUTPUT</p><pre id="water-preview-output">尚無水位紀錄。</pre><button type="button" class="primary" data-water-action="copy-water">複製最近三天</button></aside>'}</main>`; }
function renderWaterPreview(): void { const output = app.querySelector<HTMLPreElement>('#water-preview-output'); if (output && water) output.textContent = water.preview() || '尚無水位紀錄。'; }
async function mountWater(route: Extract<AppRoute, { module: 'water-level' }>, token: number): Promise<void> {
  app.innerHTML = waterShell(route.page === 'settings');
  const root = app.querySelector<HTMLElement>('#water-root');
  if (!root) throw new Error('找不到水位功能容器。');
  const module = await import('./water-level/controller.js');
  if (token !== renderToken) return;
  const controller = new module.WaterLevelController(root) as WaterController;
  water = controller;
  await controller.initialize();
  if (token !== renderToken) return;
  if (route.page === 'settings') controller.renderSettings(); else { controller.render(); renderWaterPreview(); }
}
async function renderApp(): Promise<void> {
  const token = ++renderToken; const route = parseRoute(location.hash); water = undefined;
  if (route.module === 'daily') { if (route.page === 'settings') await refreshSettings(); if (token !== renderToken) return; app.innerHTML = route.page === 'settings' ? dailySettingsView() : dailyView(); return; }
  try { await mountWater(route, token); } catch (error) { if (token !== renderToken) return; const summary = error instanceof Error ? error.message : '無法讀取本機水位資料。'; app.innerHTML = `<main class="app-shell"><section class="form-card"><h1>水位功能暫時無法開啟</h1><p>錯誤摘要：${escapeHtml(summary)}</p><p><a href="#water-level">重新載入</a>　<a href="#daily">返回施工日報</a></p></section></main>`; }
}
async function refreshSettings(): Promise<void> { const section = settingsState.activeSection; settingsTrades = await listMemories('trades'); if (section === 'templates') settingsTemplates = await listTemplates(); else if (section === 'debug') settingsDebug = await databaseSummary(); else if (section === 'trade-tasks') settingsRows = settingsState.selectedTradeTypeId ? await listMemories('tasks', settingsState.selectedTradeTypeId) : []; else if (section === 'vendors') settingsRows = settingsState.selectedTradeTypeId ? await listMemories('vendors', settingsState.selectedTradeTypeId) : []; else if (section !== 'backup') settingsRows = await listMemories(section); }
function updateDailyInput(target: HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement): void {
  const name = target.dataset.dailyField; if (!name) return;
  if (name === 'vendorNameSnapshot') return;
  const tradeId = target.closest<HTMLElement>('[data-trade]')?.dataset.trade; const workId = target.closest<HTMLElement>('[data-work]')?.dataset.work; const supplyId = target.closest<HTMLElement>('[data-supply]')?.dataset.supply; const contactId = target.closest<HTMLElement>('[data-contact]')?.dataset.contact; const specialId = target.closest<HTMLElement>('[data-special]')?.dataset.special;
  daily.update(() => { const trade = tradeId ? daily.trade(tradeId) : undefined; const work = trade?.workItems.find((item) => item.id === workId); const supply = daily.report.supplies.find((item) => item.id === supplyId); const contact = daily.report.contacts.find((item) => item.id === contactId); const special = daily.report.specialItems.find((item) => item.id === specialId); const destination = work ?? trade ?? supply ?? contact ?? special ?? daily.report; (destination as unknown as Record<string, string>)[name] = target.value; });
}
function refreshTaskSearch(target: HTMLInputElement): void { settingsState.taskSearchKeyword = target.value; void renderApp().then(() => { const search = app.querySelector<HTMLInputElement>('[data-settings-search="tasks"]'); search?.focus(); search?.setSelectionRange(search.value.length, search.value.length); }); }
app.addEventListener('compositionstart', (event) => { if ((event.target as HTMLElement).matches('[data-settings-search="tasks"]')) settingsSearchComposing = true; });
app.addEventListener('compositionend', (event) => { const target = event.target as HTMLInputElement; if (target.matches('[data-settings-search="tasks"]')) { settingsSearchComposing = false; refreshTaskSearch(target); } });
app.addEventListener('input', (event) => { const target = event.target as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement; const route = parseRoute(location.hash); if (route.module === 'water-level' && water && (target.dataset.waterField || target.dataset.waterReading)) { void water.handleInput(target); return; } if (route.module === 'daily' && route.page === 'settings' && target.dataset.settingsSearch === 'tasks') { if (!settingsSearchComposing && !(event as InputEvent).isComposing) refreshTaskSearch(target as HTMLInputElement); return; } if (route.module === 'daily' && route.page === 'settings' && target.closest('[data-settings-form]')) { settingsState.dirty = true; return; } if (route.module === 'daily' && route.page === 'main') updateDailyInput(target); });
app.addEventListener('change', (event) => { const target = event.target as HTMLInputElement | HTMLSelectElement; const route = parseRoute(location.hash); if (route.module === 'daily' && route.page === 'settings' && target.dataset.settingsField === 'trade') { if (settingsState.dirty && !window.confirm('放棄未保存修改？')) { void renderApp(); return; } settingsState.selectedTradeTypeId = target.value || null; settingsState.adding = false; settingsState.editingId = null; settingsState.dirty = false; settingsState.taskSearchKeyword = ''; void renderApp(); return; } if (route.module === 'daily' && route.page === 'main' && target.dataset.dailyField === 'vendorNameSnapshot') { const tradeId = target.closest<HTMLElement>('[data-trade]')?.dataset.trade; if (!tradeId) return; const duplicate = daily.changeVendor(tradeId, target.value, null); if (duplicate) alert('此工種與廠商已存在。'); void daily.flush(); void renderApp(); return; } if (route.module === 'daily' && route.page === 'main' && (target.dataset.dailyField === 'startFloorRaw' || target.dataset.dailyField === 'endFloorRaw')) { const workId = target.closest<HTMLElement>('[data-work]')?.dataset.work; const work = daily.report.tradeSections.flatMap((trade) => trade.workItems).find((item) => item.id === workId); if (!work) return; const normalized = normalizeFloor(target.value); if (normalized === null) { alert('樓層格式不正確，請輸入數字、B格式，或 RF／PH／MF／R1～R9。'); return; } daily.update(() => { if (target.dataset.dailyField === 'startFloorRaw') { work.startFloorRaw = normalized; work.startFloorNormalized = normalized || null; } else { work.endFloorRaw = normalized; work.endFloorNormalized = normalized || null; } const start = comparableFloor(work.startFloorNormalized); const end = comparableFloor(work.endFloorNormalized); if (start !== null && end !== null && start > end && window.confirm(`起始樓層高於結束樓層，是否交換為 ${work.endFloorNormalized}～${work.startFloorNormalized}？`)) { [work.startFloorRaw, work.endFloorRaw] = [work.endFloorRaw, work.startFloorRaw]; [work.startFloorNormalized, work.endFloorNormalized] = [work.endFloorNormalized, work.startFloorNormalized]; } }); void daily.flush(); void renderApp(); } });
app.addEventListener('click', async (event) => {
  const target = event.target as HTMLElement; const route = parseRoute(location.hash);
  // The settings action dispatcher intentionally shares one branch across heterogeneous sections.
  // @ts-ignore -- narrowed action handling below determines the applicable section.
  if (route.module === 'daily' && route.page === 'settings') { const sectionButton = target.closest<HTMLButtonElement>('[data-settings-section]'); if (sectionButton) { if (settingsState.dirty && !window.confirm('放棄未保存修改？')) return; settingsState.activeSection = sectionButton.dataset.settingsSection as DailySettingsSection; settingsState.editingId = null; settingsState.adding = false; settingsState.dirty = false; settingsState.selectedTradeTypeId = null; settingsState.taskSearchKeyword = ''; await renderApp(); return; } const actionButton = target.closest<HTMLButtonElement>('[data-settings-action]'); if (actionButton) { const action = actionButton.dataset.settingsAction!; const section = settingsState.activeSection; const id = actionButton.dataset.id!; const kind = actionButton.dataset.settingsKind as 'sites' | 'trades' | 'vendors' | 'tasks' | 'locations' | undefined; if (action === 'toggle-trade-tasks') { settingsState.selectedTradeTypeId = settingsState.selectedTradeTypeId === actionButton.dataset.tradeTypeId ? null : actionButton.dataset.tradeTypeId ?? null; settingsState.editingId = null; settingsState.adding = false; settingsState.taskSearchKeyword = ''; await renderApp(); return; } if (action === 'add-trade') { settingsState.selectedTradeTypeId = null; settingsState.adding = true; settingsState.editingId = null; } else if (action === 'add-task' || action === 'add-task-from-search') { settingsState.adding = true; settingsState.editingId = null; } else if (action === 'clear-task-search') { settingsState.taskSearchKeyword = ''; await renderApp(); app.querySelector<HTMLInputElement>('[data-settings-search="tasks"]')?.focus(); return; } else if (action === 'edit-trade' || action === 'edit-task' || action === 'edit') { settingsState.editingId = id; settingsState.adding = false; } else if (action === 'cancel') { settingsState.editingId = null; settingsState.adding = false; settingsState.dirty = false; } else if (action === 'confirm' && kind) await confirmMemory(kind as 'vendors' | 'tasks' | 'locations', id); else if (action === 'delete' && kind) { if (!window.confirm(`確定刪除「${actionButton.dataset.name ?? ''}」？\n\n此操作將影響設定記憶與目前草稿中的相關內容；既有日報快照與已複製文字不受影響。`)) return; await deleteMemory(kind, id); if (kind === 'trades' && settingsState.selectedTradeTypeId === id) { settingsState.selectedTradeTypeId = null; settingsState.taskSearchKeyword = ''; } } else if (action === 'copy-debug') await navigator.clipboard.writeText(JSON.stringify(settingsDebug, null, 2)); else if (action === 'clear-debug') { if (window.confirm('確定清除偵錯紀錄？')) await clearDebugLogs(); } await renderApp(); return; } }
  const tab = target.closest<HTMLButtonElement>('[data-daily-tab]'); if (tab && route.module === 'daily') { daily.switchTab(tab.dataset.dailyTab as DailyReportV3['activeTab']); await daily.flush(); await renderApp(); return; }
  const waterButton = target.closest<HTMLButtonElement>('[data-water-action],[data-water-view]');
  if (waterButton && route.module === 'water-level' && water) { if (waterButton.dataset.waterView) { water.mode = waterButton.dataset.waterView; water.render(); renderWaterPreview(); return; } if (waterButton.dataset.waterAction === 'copy-water') { await navigator.clipboard.writeText(water.preview()); return; } if (waterButton.dataset.waterAction) { await water.handleAction(waterButton.dataset.waterAction, waterButton.dataset.id); if (route.page === 'settings') water.renderSettings(); else renderWaterPreview(); } return; }
  const button = target.closest<HTMLButtonElement>('[data-daily-action]'); if (!button || route.module !== 'daily' || route.page !== 'main') return;
  const action = button.dataset.dailyAction!;
  if (action === 'add-trade') { tradePickerOpen = true; await renderApp(); return; }
  if (action === 'close-trade-picker') { tradePickerOpen = false; await renderApp(); return; }
  if (action === 'toggle-trade') daily.toggle(button.dataset.id!);
  else if (action === 'collapse') daily.expandedId = null;
  else if (action === 'add-work') daily.addWorkItem(button.dataset.tradeId!);
  else if (action === 'delete-work-item') daily.deleteWorkItem(button.dataset.tradeId!, button.dataset.workItemId!);
  else if (action === 'delete-trade') daily.deleteTrade(button.dataset.id!);
  else if (action === 'complete') { const issues = daily.complete(button.dataset.id!); if (issues.length) alert(`尚未完成：\n${issues.join('\n')}`); }
  else if (action === 'copy') { await navigator.clipboard.writeText(formatDailyReport(daily.report)); }
  else if (action === 'add-supply') daily.addSupply(button.dataset.type as 'concrete' | 'clsm' | 'rebar' | 'other');
  else if (action === 'add-contact') daily.addContact(); else if (action === 'add-special') daily.addSpecial();
  else if (action === 'delete-supply') daily.update(() => daily.report.supplies = daily.report.supplies.filter((item) => item.id !== button.dataset.id));
  else if (action === 'delete-contact') daily.update(() => daily.report.contacts = daily.report.contacts.filter((item) => item.id !== button.dataset.id));
  else if (action === 'delete-special') daily.update(() => daily.report.specialItems = daily.report.specialItems.filter((item) => item.id !== button.dataset.id));
  await daily.flush(); await renderApp();
});
function tradeSummary(id: string): string { const trade = daily.trade(id)!; return `<article class="trade-card trade-card--${trade.status}"><strong>${escapeHtml(trade.tradeNameSnapshot)}</strong><p>${escapeHtml(trade.vendorNameSnapshot || '尚未選擇廠商')}｜${trade.workerCount ? `${trade.workerCount}人` : '尚未填人數'}｜${trade.workItems.length}筆工項｜${trade.status === 'complete' ? '已完成' : '草稿'}</p></article>`; }
function clearTradeDrag(): void { if (tradeDrag.frame) cancelAnimationFrame(tradeDrag.frame); tradeDrag.preview?.remove(); tradeDrag.active = false; tradeDrag.id = null; tradeDrag.activeDropSlotIndex = null; tradeDrag.pointerId = null; daily.expandedId = tradeDrag.originalExpandedId; }
function resolveDropSlotIndex(pointerY: number, cards: HTMLElement[]): number { for (let index = 0; index < cards.length; index += 1) { const rect = cards[index].getBoundingClientRect(); if (pointerY < rect.top + rect.height / 2) return index; } return cards.length; }
function updateTradeDragTarget(): void { if (!tradeDrag.active) return; const cards = [...app.querySelectorAll<HTMLElement>('[data-sortable-trade]')].filter((card) => card.dataset.trade !== tradeDrag.id); const nextSlot = resolveDropSlotIndex(tradeDrag.clientY, cards); if (nextSlot === tradeDrag.activeDropSlotIndex) return; tradeDrag.activeDropSlotIndex = nextSlot; void renderApp(); }
app.addEventListener('pointerdown', (event) => { const handle = (event.target as HTMLElement).closest<HTMLElement>('[data-drag-trade]'); if (!handle || tradeDrag.active) return; const card = handle.closest<HTMLElement>('[data-trade]'); const id = handle.dataset.dragTrade; if (!card || !id) return; event.preventDefault(); const rect = card.getBoundingClientRect(); tradeDrag.active = true; tradeDrag.id = id; tradeDrag.originalOrder = daily.report.tradeSections.map((item) => item.id); tradeDrag.originalExpandedId = daily.expandedId; tradeDrag.pointerId = event.pointerId; tradeDrag.offsetX = event.clientX - rect.left; tradeDrag.offsetY = event.clientY - rect.top; tradeDrag.clientX = event.clientX; tradeDrag.clientY = event.clientY; const preview = document.createElement('div'); preview.className = 'trade-drag-preview'; preview.style.cssText = `position:fixed;z-index:1000;opacity:.8;pointer-events:none;width:${rect.width}px;left:${rect.left}px;top:${rect.top}px;box-shadow:0 10px 28px rgb(0 0 0 / 20%)`; preview.innerHTML = tradeSummary(id); document.body.append(preview); tradeDrag.preview = preview; handle.setPointerCapture(event.pointerId); void renderApp(); });
app.addEventListener('pointermove', (event) => { if (!tradeDrag.active || event.pointerId !== tradeDrag.pointerId) return; tradeDrag.clientX = event.clientX; tradeDrag.clientY = event.clientY; if (tradeDrag.preview) { tradeDrag.preview.style.left = `${event.clientX - tradeDrag.offsetX}px`; tradeDrag.preview.style.top = `${event.clientY - tradeDrag.offsetY}px`; } const edge = 100; const speed = event.clientY < edge ? -Math.round(4 + (edge - event.clientY) / edge * 14) : event.clientY > innerHeight - edge ? Math.round(4 + (event.clientY - (innerHeight - edge)) / edge * 14) : 0; if (speed) window.scrollBy(0, speed); updateTradeDragTarget(); });
app.addEventListener('pointerup', async (event) => { if (!tradeDrag.active || event.pointerId !== tradeDrag.pointerId) return; const dragged = tradeDrag.id; const slot = tradeDrag.activeDropSlotIndex; const original = [...tradeDrag.originalOrder]; if (dragged && slot !== null) { const ids = original.filter((id) => id !== dragged); ids.splice(Math.max(0, Math.min(slot, ids.length)), 0, dragged); const changed = ids.length !== original.length || ids.some((id, index) => id !== original[index]); if (changed) { const old = daily.report.tradeSections.slice(); daily.update(() => { daily.report.tradeSections = ids.map((id) => old.find((item) => item.id === id)!).filter(Boolean); daily.report.tradeSections.forEach((item, index) => item.sortOrder = index); }); try { await daily.flush(); } catch { daily.report.tradeSections = original.map((id) => old.find((item) => item.id === id)!).filter(Boolean); daily.report.tradeSections.forEach((item, index) => item.sortOrder = index); alert('排序儲存失敗，已恢復原順序。'); } } } clearTradeDrag(); await renderApp(); });
app.addEventListener('pointercancel', () => { if (tradeDrag.active) { clearTradeDrag(); void renderApp(); } });
window.addEventListener('keydown', (event) => { if (event.key === 'Escape' && tradeDrag.active) { clearTradeDrag(); void renderApp(); } });
app.addEventListener('submit', async (event) => { const form = event.target as HTMLFormElement; if (form.dataset.settingsForm) { event.preventDefault(); try { const name = String(new FormData(form).get('name') ?? ''); const section = settingsState.activeSection; const mode = form.dataset.settingsForm; if (section === 'trade-tasks') { const isTrade = mode === 'trade'; await saveMemory(isTrade ? 'trades' : 'tasks', name, isTrade ? undefined : settingsState.selectedTradeTypeId ?? undefined, isTrade && settingsState.editingId ? settingsState.editingId : !isTrade && mode === 'edit' ? settingsState.editingId ?? undefined : undefined); if (isTrade && mode === 'trade' && !settingsState.editingId) { const created = (await listMemories('trades')).find((item) => item.normalizedName === normalizeSearch(name)); settingsState.selectedTradeTypeId = created?.id ?? null; } } else if (section === 'templates') await saveTemplate(name, mode === 'edit' ? settingsState.editingId ?? undefined : undefined); else await saveMemory(section as 'sites' | 'vendors' | 'locations', name, section === 'vendors' ? settingsState.selectedTradeTypeId ?? undefined : undefined, mode === 'edit' ? settingsState.editingId ?? undefined : undefined); settingsState.adding = false; settingsState.editingId = null; settingsState.dirty = false; await renderApp(); } catch (error) { alert(error instanceof Error ? error.message : '儲存設定失敗。'); } return; } if (form.id === 'trade-picker-form') { event.preventDefault(); const values = new FormData(form); const trade = dailyTrades.find((item) => item.id === String(values.get('tradeId') ?? '')); const vendor = dailyVendors.find((item) => item.id === String(values.get('vendorId') ?? '')); if (!trade || !vendor || vendor.tradeTypeId !== trade.id) { alert('請選擇此工種所屬的廠商。'); return; } const existing = daily.findDuplicate(trade.id, trade.name, vendor.id, vendor.name); daily.addTrade(trade.name, vendor.name, trade.id, vendor.id); if (existing) alert('此工種與廠商已存在。'); tradePickerOpen = false; await daily.flush(); await renderApp(); return; } if (form.id === 'point-form' && water) { event.preventDefault(); await water.handleAction('save-point', String(new FormData(form).get('name') ?? '')); water.renderSettings(); } });
window.addEventListener('beforeunload', (event) => { if (settingsState.dirty && parseRoute(location.hash).page === 'settings') { event.preventDefault(); event.returnValue = ''; } });
window.addEventListener('hashchange', () => { if (parseRoute(location.hash).module === 'water-level') void daily.flush(); void renderApp(); });
document.addEventListener('visibilitychange', () => { if (document.hidden) void daily.flush(); });
async function bootstrap(): Promise<void> { daily = new DailyController(await loadDailyDraft()); dailyTrades = await listMemories('trades'); dailyVendors = await listMemories('vendors'); if (!location.hash) location.hash = '#daily'; await renderApp(); if ('serviceWorker' in navigator && import.meta.env.PROD) navigator.serviceWorker.register(`${import.meta.env.BASE_URL}service-worker.js`).catch(() => undefined); }
bootstrap().catch(() => { app.innerHTML = '<main class="app-shell"><h1>無法開啟施工日報</h1><p>請確認瀏覽器允許本機資料儲存。</p></main>'; });
