-- Consolidated sync hardening; generated by Supabase CLI.
-- Source repairs are retained for incident history, not loaded by CI.
begin;
-- Included by the audit hardening migration; not a standalone deployment script.
create or replace function public.audit_assert_json(p_value jsonb, p_depth integer default 0)
returns void language plpgsql immutable set search_path = public, pg_temp as $$
declare k text; v jsonb;
begin
  if p_value is null or p_depth > 24 or octet_length(p_value::text) > 1048576 then
    raise exception 'invalid payload size or depth' using errcode='22023';
  end if;
  if jsonb_typeof(p_value) = 'array' then
    if jsonb_array_length(p_value) > 10000 then raise exception 'too many rows' using errcode='22023'; end if;
    for v in select value from jsonb_array_elements(p_value) loop perform public.audit_assert_json(v, p_depth+1); end loop;
  elsif jsonb_typeof(p_value) = 'object' then
    for k,v in select * from jsonb_each(p_value) loop
      if k in ('__proto__','constructor','prototype') then raise exception 'invalid key' using errcode='22023'; end if;
      if (k='id' or right(k,2)='Id') and v <> 'null'::jsonb and v <> '""'::jsonb then
        if jsonb_typeof(v) <> 'string' or (v #>> '{}') !~ '^[a-zA-Z0-9_:.-]{1,128}$' then
          raise exception 'invalid identifier' using errcode='22023';
        end if;
      end if;
      perform public.audit_assert_json(v, p_depth+1);
    end loop;
  end if;
end $$;

create or replace function public.audit_assert_changes(p_kind text, p_changes jsonb)
returns void language plpgsql immutable set search_path = public, pg_temp as $$
declare c jsonb; col text; op text; field text; allowed text[]; k text; v jsonb; child jsonb;
begin
  perform public.audit_assert_json(p_changes);
  if jsonb_typeof(p_changes) is distinct from 'array' or jsonb_array_length(p_changes)>5000 then raise exception 'invalid changes' using errcode='22023'; end if;
  for c in select value from jsonb_array_elements(p_changes) loop
    if jsonb_typeof(c) is distinct from 'object' then raise exception 'invalid change' using errcode='22023'; end if;
    for k in select jsonb_object_keys(c) loop
      if k not in ('collection','op','id','parentId','field','value','ids') then raise exception 'unexpected change key' using errcode='22023'; end if;
    end loop;
    col := c->>'collection'; op := c->>'op';
    if col is null or op is null or op not in ('set','upsert','delete','order')
      or (p_kind='daily' and col not in ('$document','tradeSections','workItems','standaloneMaterialEntries','supplies','contacts','specialItems'))
      or (p_kind='water' and col not in ('$document','points','logs','readings')) then raise exception 'invalid collection or operation' using errcode='22023'; end if;
    if col in ('workItems','readings') and coalesce(c->>'parentId','')='' then raise exception 'missing parent' using errcode='22023'; end if;
    if col not in ('workItems','readings') and c ? 'parentId' then raise exception 'unexpected parent' using errcode='22023'; end if;
    if op='order' then
      if col='$document' or jsonb_typeof(c->'ids') is distinct from 'array' then raise exception 'invalid order' using errcode='22023'; end if;
      for v in select value from jsonb_array_elements(c->'ids') loop
        if jsonb_typeof(v)<>'string' or (v #>> '{}') !~ '^[a-zA-Z0-9_:.-]{1,128}$' then raise exception 'invalid order id' using errcode='22023'; end if;
      end loop;
      continue;
    end if;
    if coalesce(c->>'id','')='' then raise exception 'missing id' using errcode='22023'; end if;
    if col='$document' then
      if op<>'set' or c->>'id' is distinct from p_kind or
        (p_kind='daily' and coalesce(c->>'field','') not in ('siteId','siteNameSnapshot','activeTab')) or
        (p_kind='water' and coalesce(c->>'field','')<>'schemaVersion') then raise exception 'invalid document field' using errcode='22023'; end if;
    end if;
    allowed := case col
      when '$document' then array['siteId','siteNameSnapshot','activeTab','schemaVersion']
      when 'tradeSections' then array['tradeTypeId','tradeNameSnapshot','vendorId','vendorNameSnapshot','workerCount','status','sortOrder','workItems','materialEntries']
      when 'workItems' then array['startFloorRaw','startFloorNormalized','endFloorRaw','endFloorNormalized','locationId','locationTextSnapshot','taskId','taskTextSnapshot','note','sortOrder']
      when 'standaloneMaterialEntries' then array['entryType','connectedTradeSectionId','materialTypeId','materialTypeSnapshot','itemName','supplierId','supplierNameSnapshot','quantity','unit','specification','note','sortOrder']
      when 'supplies' then array['type','name','strength','quantity','unit','sortOrder']
      when 'contacts' then array['tradeTypeId','tradeNameSnapshot','vendorId','vendorNameSnapshot','items','sortOrder']
      when 'specialItems' then array['content','sortOrder']
      when 'points' then array['name','normalizedName','sortOrder']
      when 'logs' then array['measuredAt','battery','readings']
      when 'readings' then array['pointNameSnapshot','value','change','sourceChange'] end;
    if op='set' then
      field := c->>'field';
      if field is null or not field=any(allowed) or field in ('workItems','readings') or not c ? 'value' then raise exception 'invalid field' using errcode='22023'; end if;
    elsif op='upsert' then
      if jsonb_typeof(c->'value') is distinct from 'object' or c->'value'->>(case when col='readings' then 'pointId' else 'id' end) is distinct from c->>'id' then raise exception 'identity mismatch' using errcode='22023'; end if;
      for k in select jsonb_object_keys(c->'value') loop
        if not k=any(allowed || array['id','pointId','createdAt','updatedAt']) then raise exception 'unexpected field' using errcode='22023'; end if;
      end loop;
    end if;
    -- Scalar fields cannot smuggle arrays/objects; arrays are explicitly named.
    for k,v in select * from jsonb_each(case when op='set' then jsonb_build_object(c->>'field', c->'value') when op='upsert' then c->'value' else '{}'::jsonb end) loop
      if k in ('items','workItems','materialEntries','readings') then
        if jsonb_typeof(v)<>'array' then raise exception 'expected array' using errcode='22023'; end if;
        for child in select value from jsonb_array_elements(v) loop
          if jsonb_typeof(child) is distinct from 'object' then raise exception 'invalid nested row' using errcode='22023'; end if;
          if k='items' then
            if coalesce(child->>'id','')='' or jsonb_typeof(child->'content') is distinct from 'string' then raise exception 'invalid contact item' using errcode='22023'; end if;
            perform public.audit_assert_changes('daily',jsonb_build_array(jsonb_build_object('collection','specialItems','op','upsert','id',child->>'id','value',child)));
          else
            perform public.audit_assert_changes(p_kind,jsonb_build_array(jsonb_build_object('collection',case when k='materialEntries' then 'standaloneMaterialEntries' else k end,'op','upsert','id',child->>(case when k='readings' then 'pointId' else 'id' end),'value',child) || case when k in ('workItems','readings') then jsonb_build_object('parentId',c->>'id') else '{}'::jsonb end));
          end if;
        end loop;
      elsif k in ('sortOrder','schemaVersion','change','sourceChange') then
        if jsonb_typeof(v) not in ('number','null') then raise exception 'expected number' using errcode='22023'; end if;
      elsif k in ('value','battery') then
        if jsonb_typeof(v) not in ('number','string') then raise exception 'expected numeric input' using errcode='22023'; end if;
        if v <> '""'::jsonb and (v #>> '{}') !~ '^[+-]?[0-9]+([.][0-9]+)?$' then raise exception 'invalid numeric input' using errcode='22023'; end if;
        if k='value' and v <> '""'::jsonb and (v #>> '{}')::numeric<=0 then raise exception 'invalid reading' using errcode='22023'; end if;
      elsif jsonb_typeof(v) not in ('string','null') then raise exception 'expected text' using errcode='22023';
      end if;
      if k='status' and (v #>> '{}') not in ('draft','complete') then raise exception 'invalid trade status' using errcode='22023'; end if;
      if k='entryType' and (v #>> '{}') not in ('normal','independent') then raise exception 'invalid material type' using errcode='22023'; end if;
      if k='activeTab' and (v #>> '{}') not in ('engineering','supplies','contacts','special') then raise exception 'invalid tab' using errcode='22023'; end if;
    end loop;
  end loop;
end $$;
revoke all on function public.audit_assert_json(jsonb,integer), public.audit_assert_changes(text,jsonb) from public, anon;


create or replace function public.apply_daily_field_mutation(p_site_id uuid, p_mutation_id uuid, p_entity_id uuid, p_report_date date, p_changes jsonb)
returns jsonb language plpgsql security definer set search_path = public, extensions, pg_temp as $$
declare v_user uuid := auth.uid(); v_hash text; v_prior public.sync_operations; v_row public.daily_drafts; v_change jsonb; v_payload jsonb; v_sequence bigint; v_result jsonb; v_deleted boolean;
begin
  -- Authenticate and authorize BEFORE taking the site lock or parsing the payload,
  -- so callers without edit access can neither stall the site nor spend CPU on JSON.
  if auth.uid() is null then raise exception 'authentication required' using errcode = '28000'; end if;
  if not public.can_edit_site(p_site_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended('audit-site:' || p_site_id::text, 0));
  if v_user is null then raise exception 'authentication required' using errcode = '28000'; end if;
  if not public.can_edit_site(p_site_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  if jsonb_typeof(p_changes) <> 'array' then raise exception 'invalid changes' using errcode = '22023'; end if;
  if p_report_date is null or p_entity_id is null then raise exception 'missing document identity' using errcode='22023'; end if;
  perform public.audit_assert_changes('daily',p_changes);
  v_hash := encode(digest(concat_ws('|',p_site_id::text,p_entity_id::text,p_report_date::text,p_changes::text),'sha256'),'hex');
  select * into v_prior from public.sync_operations where site_id=p_site_id and user_id=v_user and mutation_id=p_mutation_id;
  if found then if v_prior.request_hash <> v_hash then raise exception 'mutation id reused with different payload' using errcode='22023'; end if; return v_prior.result || jsonb_build_object('replayed',true); end if;
  select * into v_row from public.daily_drafts where site_id=p_site_id and report_date=p_report_date for update;
  v_payload := coalesce(v_row.payload, jsonb_build_object('date',p_report_date::text,'tradeSections','[]'::jsonb,'standaloneMaterialEntries','[]'::jsonb,'supplies','[]'::jsonb,'contacts','[]'::jsonb,'specialItems','[]'::jsonb));
  for v_change in select value from jsonb_array_elements(p_changes) loop
    select exists(select 1 from public.collaboration_tombstones where site_id=p_site_id and document_kind='daily' and collection=v_change->>'collection' and entity_id=v_change->>'id' and parent_id=coalesce(v_change->>'parentId','')) into v_deleted;
    if v_deleted and v_change->>'op' <> 'delete' then continue; end if;
    if v_change->>'op' = 'delete' then insert into public.collaboration_tombstones(site_id,document_kind,collection,entity_id,parent_id) values(p_site_id,'daily',v_change->>'collection',v_change->>'id',coalesce(v_change->>'parentId','')) on conflict do nothing; end if;
    v_payload := public.collaboration_apply_change(v_payload, 'daily', v_change);
  end loop;
  insert into public.daily_drafts(id,site_id,report_date,payload,revision,updated_by) values(p_entity_id,p_site_id,p_report_date,v_payload,1,v_user)
    on conflict(site_id,report_date) do update set payload=excluded.payload, revision=public.daily_drafts.revision+1, updated_by=v_user, updated_at=now(), deleted_at=null returning * into v_row;
  insert into public.site_sync_state(site_id,last_sequence) values(p_site_id,0) on conflict do nothing; update public.site_sync_state set last_sequence=last_sequence+1 where site_id=p_site_id returning last_sequence into v_sequence;
  insert into public.site_changes(site_id,sequence,entity,entity_id,operation,revision) values(p_site_id,v_sequence,'daily-draft',v_row.id,'upsert',v_row.revision);
  v_result := jsonb_build_object('status','applied','entity_id',v_row.id,'revision',v_row.revision,'sequence',v_sequence);
  insert into public.sync_operations(site_id,user_id,mutation_id,request_hash,result) values(p_site_id,v_user,p_mutation_id,v_hash,v_result); return v_result;
end $$;

create or replace function public.apply_water_field_mutation(p_site_id uuid, p_mutation_id uuid, p_changes jsonb)
returns jsonb language plpgsql security definer set search_path = public, extensions, pg_temp as $$
declare v_user uuid := auth.uid(); v_hash text; v_prior public.sync_operations; v_row public.water_snapshots; v_change jsonb; v_payload jsonb := jsonb_build_object('schemaVersion',1,'points','[]'::jsonb,'logs','[]'::jsonb); v_sequence bigint; v_result jsonb; v_deleted boolean;
begin
  -- Authenticate and authorize BEFORE taking the site lock or parsing the payload,
  -- so callers without edit access can neither stall the site nor spend CPU on JSON.
  if auth.uid() is null then raise exception 'authentication required' using errcode = '28000'; end if;
  if not public.can_edit_site(p_site_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended('audit-site:' || p_site_id::text, 0));
  if v_user is null then raise exception 'authentication required' using errcode='28000'; end if; if not public.can_edit_site(p_site_id) then raise exception 'forbidden' using errcode='42501'; end if;
  if jsonb_typeof(p_changes) <> 'array' then raise exception 'invalid changes' using errcode='22023'; end if;
  perform public.audit_assert_changes('water',p_changes);
  v_hash := encode(digest(concat_ws('|',p_site_id::text,p_changes::text),'sha256'),'hex'); select * into v_prior from public.sync_operations where site_id=p_site_id and user_id=v_user and mutation_id=p_mutation_id;
  if found then if v_prior.request_hash <> v_hash then raise exception 'mutation id reused with different payload' using errcode='22023'; end if; return v_prior.result || jsonb_build_object('replayed',true); end if;
  select * into v_row from public.water_snapshots where site_id=p_site_id for update; v_payload := coalesce(v_row.payload,v_payload);
  for v_change in select value from jsonb_array_elements(p_changes) loop
    select exists(select 1 from public.collaboration_tombstones where site_id=p_site_id and document_kind='water' and collection=v_change->>'collection' and entity_id=v_change->>'id' and parent_id=coalesce(v_change->>'parentId','')) into v_deleted;
    if v_deleted and v_change->>'op' <> 'delete' then continue; end if;
    if v_change->>'op' = 'delete' then insert into public.collaboration_tombstones(site_id,document_kind,collection,entity_id,parent_id) values(p_site_id,'water',v_change->>'collection',v_change->>'id',coalesce(v_change->>'parentId','')) on conflict do nothing; end if;
    v_payload := public.collaboration_apply_change(v_payload, 'water', v_change);
  end loop;
  insert into public.water_snapshots(site_id,payload,revision,updated_by) values(p_site_id,v_payload,1,v_user) on conflict(site_id) do update set payload=excluded.payload,revision=public.water_snapshots.revision+1,updated_by=v_user,updated_at=now() returning * into v_row;
  insert into public.site_sync_state(site_id,last_sequence) values(p_site_id,0) on conflict do nothing; update public.site_sync_state set last_sequence=last_sequence+1 where site_id=p_site_id returning last_sequence into v_sequence;
  insert into public.site_changes(site_id,sequence,entity,entity_id,operation,revision) values(p_site_id,v_sequence,'water-snapshot',p_site_id,'upsert',v_row.revision);
  v_result:=jsonb_build_object('status','applied','entity_id',p_site_id,'revision',v_row.revision,'sequence',v_sequence); insert into public.sync_operations(site_id,user_id,mutation_id,request_hash,result) values(p_site_id,v_user,p_mutation_id,v_hash,v_result); return v_result;
end $$;

create or replace function public.apply_daily_draft_mutation(
  p_site_id uuid,
  p_mutation_id uuid,
  p_entity_id uuid,
  p_base_revision bigint,
  p_payload jsonb
) returns jsonb
language plpgsql security definer set search_path = public, extensions, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_request_hash text;
  v_prior public.sync_operations;
  v_current public.daily_drafts;
  v_sequence bigint;
  v_result jsonb;
  v_report_date date;
begin
  -- Authenticate and authorize BEFORE taking the site lock or parsing the payload,
  -- so callers without edit access can neither stall the site nor spend CPU on JSON.
  if auth.uid() is null then raise exception 'authentication required' using errcode = '28000'; end if;
  if not public.can_edit_site(p_site_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended('audit-site:' || p_site_id::text, 0));
  perform public.audit_assert_json(p_payload);
  if v_user_id is null then raise exception 'authentication required' using errcode = '28000'; end if;
  if not public.can_edit_site(p_site_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  v_report_date := (p_payload ->> 'date')::date;
  if v_report_date is null then raise exception 'missing report date' using errcode = '22023'; end if;
  v_request_hash := encode(digest(concat_ws('|', p_site_id::text, p_entity_id::text, p_base_revision::text, p_payload::text), 'sha256'), 'hex');

  select * into v_prior from public.sync_operations
    where site_id = p_site_id and user_id = v_user_id and mutation_id = p_mutation_id;
  if found then
    if v_prior.request_hash <> v_request_hash then raise exception 'mutation id reused with different payload' using errcode = '22023'; end if;
    return v_prior.result || jsonb_build_object('replayed',true);
  end if;

  select * into v_current from public.daily_drafts
    where site_id = p_site_id and (id = p_entity_id or report_date = v_report_date)
    order by (id = p_entity_id) desc limit 1 for update;

  if found and v_current.revision <> p_base_revision then
    v_result := jsonb_build_object('status', 'conflict', 'entity_id', v_current.id, 'revision', v_current.revision, 'remote_payload', v_current.payload);
    insert into public.sync_operations(site_id, user_id, mutation_id, request_hash, result)
      values (p_site_id, v_user_id, p_mutation_id, v_request_hash, v_result);
    return v_result;
  end if;
  if not found and p_base_revision <> 0 then
    v_result := jsonb_build_object('status', 'conflict', 'entity_id', p_entity_id, 'revision', 0, 'remote_payload', null);
    insert into public.sync_operations(site_id, user_id, mutation_id, request_hash, result)
      values (p_site_id, v_user_id, p_mutation_id, v_request_hash, v_result);
    return v_result;
  end if;

  if found then
    update public.daily_drafts set payload = p_payload, revision = revision + 1, updated_by = v_user_id, updated_at = now(), deleted_at = null
      where id = v_current.id returning * into v_current;
  else
    insert into public.daily_drafts(id, site_id, report_date, payload, revision, updated_by)
      values (p_entity_id, p_site_id, v_report_date, p_payload, 1, v_user_id) returning * into v_current;
  end if;

  insert into public.site_sync_state(site_id, last_sequence) values (p_site_id, 0) on conflict (site_id) do nothing;
  update public.site_sync_state set last_sequence = last_sequence + 1 where site_id = p_site_id returning last_sequence into v_sequence;
  insert into public.site_changes(site_id, sequence, entity, entity_id, operation, revision)
    values (p_site_id, v_sequence, 'daily-draft', v_current.id, 'upsert', v_current.revision);

  v_result := jsonb_build_object('status', 'applied', 'entity_id', v_current.id, 'revision', v_current.revision, 'sequence', v_sequence);
  insert into public.sync_operations(site_id, user_id, mutation_id, request_hash, result)
    values (p_site_id, v_user_id, p_mutation_id, v_request_hash, v_result);
  return v_result;
end $$;

create or replace function public.apply_water_snapshot_mutation(
  p_site_id uuid, p_mutation_id uuid, p_base_revision bigint, p_payload jsonb
) returns jsonb language plpgsql security definer set search_path = public, extensions, pg_temp
as $$
declare v_user_id uuid := auth.uid(); v_hash text; v_prior public.sync_operations; v_current public.water_snapshots; v_sequence bigint; v_result jsonb;
begin
  -- Authenticate and authorize BEFORE taking the site lock or parsing the payload,
  -- so callers without edit access can neither stall the site nor spend CPU on JSON.
  if auth.uid() is null then raise exception 'authentication required' using errcode = '28000'; end if;
  if not public.can_edit_site(p_site_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended('audit-site:' || p_site_id::text, 0));
  perform public.audit_assert_json(p_payload);
  if v_user_id is null then raise exception 'authentication required' using errcode = '28000'; end if;
  if not public.can_edit_site(p_site_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  if coalesce(p_payload ->> 'schemaVersion','') <> '1' or coalesce(jsonb_typeof(p_payload -> 'points'),'') <> 'array' or coalesce(jsonb_typeof(p_payload -> 'logs'),'') <> 'array' then
    raise exception 'invalid water snapshot' using errcode = '22023';
  end if;
  v_hash := encode(digest(concat_ws('|',p_site_id::text,p_base_revision::text,p_payload::text),'sha256'),'hex');
  select * into v_prior from public.sync_operations where site_id=p_site_id and user_id=v_user_id and mutation_id=p_mutation_id;
  if found then
    if v_prior.request_hash <> v_hash then raise exception 'mutation id reused with different payload' using errcode = '22023'; end if;
    return v_prior.result || jsonb_build_object('replayed',true);
  end if;
  select * into v_current from public.water_snapshots where site_id=p_site_id for update;
  if found and v_current.revision <> p_base_revision then
    v_result := jsonb_build_object('status','conflict','entity_id',p_site_id,'revision',v_current.revision,'remote_payload',v_current.payload);
    insert into public.sync_operations(site_id,user_id,mutation_id,request_hash,result) values(p_site_id,v_user_id,p_mutation_id,v_hash,v_result); return v_result;
  end if;
  if not found and p_base_revision <> 0 then
    v_result := jsonb_build_object('status','conflict','entity_id',p_site_id,'revision',0,'remote_payload',null);
    insert into public.sync_operations(site_id,user_id,mutation_id,request_hash,result) values(p_site_id,v_user_id,p_mutation_id,v_hash,v_result); return v_result;
  end if;
  insert into public.water_snapshots(site_id,payload,revision,updated_by) values(p_site_id,p_payload,1,v_user_id)
    on conflict(site_id) do update set payload=excluded.payload,revision=public.water_snapshots.revision+1,updated_by=v_user_id,updated_at=now()
    returning * into v_current;
  insert into public.site_sync_state(site_id,last_sequence) values(p_site_id,0) on conflict(site_id) do nothing;
  update public.site_sync_state set last_sequence=last_sequence+1 where site_id=p_site_id returning last_sequence into v_sequence;
  insert into public.site_changes(site_id,sequence,entity,entity_id,operation,revision)
    values(p_site_id,v_sequence,'water-snapshot',p_site_id,'upsert',v_current.revision);
  v_result := jsonb_build_object('status','applied','entity_id',p_site_id,'revision',v_current.revision,'sequence',v_sequence);
  insert into public.sync_operations(site_id,user_id,mutation_id,request_hash,result) values(p_site_id,v_user_id,p_mutation_id,v_hash,v_result);
  return v_result;
end $$;

create or replace function public.apply_memory_snapshot_mutation(
  p_site_id uuid, p_mutation_id uuid, p_base_revision bigint, p_payload jsonb
) returns jsonb language plpgsql security definer set search_path = public, extensions, pg_temp
as $$
declare v_user_id uuid := auth.uid(); v_hash text; v_prior public.sync_operations; v_current public.memory_snapshots; v_sequence bigint; v_result jsonb;
begin
  -- Authenticate and authorize BEFORE taking the site lock or parsing the payload,
  -- so callers without edit access can neither stall the site nor spend CPU on JSON.
  if auth.uid() is null then raise exception 'authentication required' using errcode = '28000'; end if;
  if not public.can_edit_site(p_site_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended('audit-site:' || p_site_id::text, 0));
  perform public.audit_assert_json(p_payload);
  if v_user_id is null then raise exception 'authentication required' using errcode = '28000'; end if;
  if not public.can_edit_site(p_site_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  if coalesce(p_payload ->> 'schemaVersion','') <> '1' or coalesce(jsonb_typeof(p_payload -> 'stores'),'') <> 'object' then raise exception 'invalid memory snapshot' using errcode = '22023'; end if;
  v_hash := encode(digest(concat_ws('|', p_site_id::text, p_base_revision::text, p_payload::text), 'sha256'), 'hex');
  select * into v_prior from public.sync_operations where site_id = p_site_id and user_id = v_user_id and mutation_id = p_mutation_id;
  if found then
    if v_prior.request_hash <> v_hash then raise exception 'mutation id reused with different payload' using errcode = '22023'; end if;
    return v_prior.result || jsonb_build_object('replayed',true);
  end if;
  select * into v_current from public.memory_snapshots where site_id = p_site_id for update;
  if found and v_current.revision <> p_base_revision then
    v_result := jsonb_build_object('status','conflict','entity_id',p_site_id,'revision',v_current.revision,'remote_payload',v_current.payload);
    insert into public.sync_operations(site_id,user_id,mutation_id,request_hash,result,created_at)
      values (p_site_id,v_user_id,p_mutation_id,v_hash,v_result,now()); return v_result;
  end if;
  if not found and p_base_revision <> 0 then
    v_result := jsonb_build_object('status','conflict','entity_id',p_site_id,'revision',0,'remote_payload',null);
    insert into public.sync_operations(site_id,user_id,mutation_id,request_hash,result,created_at)
      values (p_site_id,v_user_id,p_mutation_id,v_hash,v_result,now()); return v_result;
  end if;
  insert into public.memory_snapshots(site_id,payload,revision,updated_by) values(p_site_id,p_payload,1,v_user_id)
    on conflict(site_id) do update set payload=excluded.payload, revision=public.memory_snapshots.revision+1, updated_by=v_user_id, updated_at=now()
    returning * into v_current;
  insert into public.site_sync_state(site_id,last_sequence) values(p_site_id,0) on conflict(site_id) do nothing;
  update public.site_sync_state set last_sequence=last_sequence+1 where site_id=p_site_id returning last_sequence into v_sequence;
  insert into public.site_changes(site_id,sequence,entity,entity_id,operation,revision,changed_at)
    values(p_site_id,v_sequence,'memory',p_site_id,'upsert',v_current.revision,now());
  v_result := jsonb_build_object('status','applied','entity_id',p_site_id,'revision',v_current.revision,'sequence',v_sequence);
  insert into public.sync_operations(site_id,user_id,mutation_id,request_hash,result,created_at)
    values(p_site_id,v_user_id,p_mutation_id,v_hash,v_result,now()); return v_result;
end $$;

create or replace function public.apply_memory_entry_mutation(
  p_site_id uuid, p_mutation_id uuid, p_base_revision bigint, p_entry jsonb
) returns jsonb language plpgsql security definer set search_path=public,extensions,pg_temp
as $$
declare v_user uuid := auth.uid(); v_id uuid; v_parent uuid; v_kind text; v_name text;
  v_status text; v_payload jsonb; v_hash text; v_prior public.sync_operations;
  v_current public.memory_entries; v_result jsonb; v_revision bigint; v_sequence bigint;
  v_deleted boolean; v_usage integer; v_finalized integer;
  v_learning_key text; v_delta_usage integer; v_delta_finalized integer;
begin
  -- Authenticate and authorize BEFORE taking the site lock or parsing the payload,
  -- so callers without edit access can neither stall the site nor spend CPU on JSON.
  if auth.uid() is null then raise exception 'authentication required' using errcode = '28000'; end if;
  if not public.can_edit_site(p_site_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended('audit-site:' || p_site_id::text, 0));
  perform public.audit_assert_json(p_entry);
  if v_user is null then raise exception 'authentication required' using errcode='28000'; end if;
  if not public.can_edit_site(p_site_id) then raise exception 'forbidden' using errcode='42501'; end if;
  v_id := (p_entry->>'id')::uuid;
  v_kind := p_entry->>'kind'; v_parent := nullif(p_entry->>'parent_id','')::uuid;
  v_name := p_entry->>'normalized_name'; v_status := p_entry->>'status';
  v_payload := p_entry->'payload'; v_deleted := coalesce((p_entry->>'deleted')::boolean,false);
  v_learning_key := nullif(p_entry->>'learning_key','');
  v_delta_usage := coalesce((p_entry->'learning_delta'->>'usage')::integer,0);
  v_delta_finalized := coalesce((p_entry->'learning_delta'->>'finalized')::integer,0);
  v_usage := (p_entry->>'usage_count')::integer; v_finalized := (p_entry->>'finalized_usage_count')::integer;
  if v_id is null or v_kind not in ('site','trade','vendor','task','location','material-type','material-item','template')
    or v_name is null or v_name='' or v_status not in ('candidate','confirmed')
    or jsonb_typeof(v_payload)<>'object' or v_payload->>'id'<>v_id::text
    or v_usage<0 or v_finalized<0 or v_finalized>v_usage
    or p_base_revision<0 or length(coalesce(v_learning_key,''))>128
    or v_delta_usage<0 or v_delta_finalized<0 or v_delta_finalized>v_delta_usage
    or (v_learning_key is null and p_entry ? 'learning_delta')
    then raise exception 'invalid memory entry' using errcode='22023'; end if;
  if v_name is distinct from (case when v_kind='material-item' then coalesce(v_payload->>'fieldType','')||':'||coalesce(v_payload->>'normalizedValue','')
    else v_payload->>'normalizedName' end)
    or (v_kind<>'template' and coalesce(v_payload->>'status','confirmed')<>v_status)
    or (v_kind in ('vendor','task') and nullif(v_payload->>'tradeTypeId','')::uuid is distinct from v_parent)
    or (v_kind='material-item' and nullif(v_payload->>'materialTypeId','')::uuid is distinct from v_parent)
    then raise exception 'memory entry fields mismatch' using errcode='22023'; end if;
  if (v_kind in ('vendor','task','material-item')) <> (v_parent is not null) then
    raise exception 'invalid memory parent' using errcode='22023'; end if;
  v_hash := encode(digest(concat_ws('|',p_site_id::text,p_base_revision::text,p_entry::text),'sha256'),'hex');
  select * into v_prior from public.sync_operations where site_id=p_site_id and user_id=v_user and mutation_id=p_mutation_id;
  if found then
    if v_prior.request_hash<>v_hash then raise exception 'mutation id reused with different payload' using errcode='22023'; end if;
    return v_prior.result || jsonb_build_object('replayed',true);
  end if;
  select * into v_current from public.memory_entries where id=v_id and site_id=p_site_id for update;
  if v_learning_key is not null and exists(select 1 from public.memory_learning_events
    where site_id=p_site_id and entry_id=v_id and learning_key=v_learning_key) then
    select revision into v_revision from public.memory_entries where id=v_id and site_id=p_site_id;
    v_result:=jsonb_build_object('status','duplicate','entity_id',v_id,'revision',v_revision);
    insert into public.sync_operations(site_id,user_id,mutation_id,request_hash,result)
      values(p_site_id,v_user,p_mutation_id,v_hash,v_result);
    return v_result;
  end if;
  if v_parent is not null and not exists(
    select 1 from public.memory_entries where id=v_parent and site_id=p_site_id and deleted_at is null
      and kind=case when v_kind='material-item' then 'material-type' else 'trade' end
  ) then raise exception 'memory parent missing' using errcode='23503'; end if;
  if v_current.id is not null then
    if v_current.deleted_at is not null and v_learning_key is not null then
      v_result:=jsonb_build_object('status','conflict','entity_id',v_id,'revision',v_current.revision,'remote_payload',to_jsonb(v_current));
    elsif v_learning_key is not null then
      v_usage := v_current.usage_count+v_delta_usage;
      v_finalized := v_current.finalized_usage_count+v_delta_finalized;
      v_status := case when v_current.status='confirmed' or v_usage>=4 then 'confirmed' else 'candidate' end;
      v_payload := v_current.payload || jsonb_build_object('usageCount',v_usage,'finalizedUsageCount',v_finalized,
        'status',v_status,'lastUsedAt',greatest(coalesce(v_current.payload->>'lastUsedAt',''),coalesce(v_payload->>'lastUsedAt','')));
      update public.memory_entries set payload=v_payload,status=v_status,usage_count=v_usage,finalized_usage_count=v_finalized,
        revision=revision+1,updated_by=v_user,updated_at=now() where id=v_id returning revision into v_revision;
    elsif v_current.revision<>p_base_revision then
      v_result:=jsonb_build_object('status','conflict','entity_id',v_id,'revision',v_current.revision,'remote_payload',to_jsonb(v_current));
    else
      -- Administrative edits do not replace server-owned usage totals.
      v_usage := v_current.usage_count; v_finalized := v_current.finalized_usage_count;
      v_status := case when v_status='confirmed' or v_usage>=4 then 'confirmed' else 'candidate' end;
      v_payload := v_payload || jsonb_build_object('usageCount',v_usage,'finalizedUsageCount',v_finalized,'status',v_status);
      update public.memory_entries set kind=v_kind,parent_id=v_parent,normalized_name=v_name,payload=v_payload,status=v_status,
        usage_count=v_usage,finalized_usage_count=v_finalized,revision=revision+1,updated_by=v_user,updated_at=now(),
        deleted_at=case when v_deleted then now() else null end where id=v_id returning revision into v_revision;
    end if;
  elsif p_base_revision<>0 then
    v_result:=jsonb_build_object('status','conflict','entity_id',v_id,'revision',0,'remote_payload',null);
  else
    begin
      insert into public.memory_entries(id,site_id,kind,parent_id,normalized_name,payload,status,usage_count,finalized_usage_count,updated_by,deleted_at)
        values(v_id,p_site_id,v_kind,v_parent,v_name,v_payload,v_status,v_usage,v_finalized,v_user,case when v_deleted then now() else null end)
        returning revision into v_revision;
    exception when unique_violation then
      select * into v_current from public.memory_entries
        where site_id=p_site_id and kind=v_kind and parent_id is not distinct from v_parent
          and normalized_name=v_name and deleted_at is null
        for update;
      if v_current.id is null then raise; end if;
      v_result:=jsonb_build_object(
        'status','duplicate','entity_id',v_current.id,'revision',v_current.revision,
        'remote_payload',jsonb_build_object(
          'id',v_current.id,'kind',v_current.kind,'parent_id',v_current.parent_id,
          'normalized_name',v_current.normalized_name,'payload',v_current.payload,
          'status',v_current.status,'usage_count',v_current.usage_count,
          'finalized_usage_count',v_current.finalized_usage_count,'revision',v_current.revision,
          'deleted_at',v_current.deleted_at
        )
      );
    end;
  end if;
  if v_result is null then
    if v_learning_key is not null then
      insert into public.memory_learning_events(site_id,entry_id,learning_key) values(p_site_id,v_id,v_learning_key);
    end if;
    insert into public.site_sync_state(site_id,last_sequence) values(p_site_id,0) on conflict(site_id) do nothing;
    update public.site_sync_state set last_sequence=last_sequence+1 where site_id=p_site_id returning last_sequence into v_sequence;
    insert into public.site_changes(site_id,sequence,entity,entity_id,operation,revision)
      values(p_site_id,v_sequence,'memory-entry',v_id,case when v_deleted then 'delete' else 'upsert' end,v_revision);
    v_result:=jsonb_build_object('status','applied','entity_id',v_id,'revision',v_revision,'sequence',v_sequence);
  end if;
  insert into public.sync_operations(site_id,user_id,mutation_id,request_hash,result)
    values(p_site_id,v_user,p_mutation_id,v_hash,v_result);
  return v_result;
end $$;

create or replace function public.apply_memory_application(
  p_site_id uuid, p_mutation_id uuid, p_base_revision bigint, p_entry jsonb
) returns jsonb language plpgsql security definer set search_path=public,extensions,pg_temp
as $$
declare v_user uuid := auth.uid(); v_id uuid; v_parent uuid; v_kind text; v_name text;
  v_status text; v_payload jsonb; v_hash text; v_prior public.sync_operations;
  v_current public.memory_entries; v_result jsonb; v_revision bigint; v_sequence bigint;
  v_deleted boolean; v_usage integer; v_finalized integer;
  v_learning_key text; v_delta_usage integer; v_delta_finalized integer;
begin
  -- Authenticate and authorize BEFORE taking the site lock or parsing the payload,
  -- so callers without edit access can neither stall the site nor spend CPU on JSON.
  if auth.uid() is null then raise exception 'authentication required' using errcode = '28000'; end if;
  if not public.can_edit_site(p_site_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended('audit-site:' || p_site_id::text, 0));
  perform public.audit_assert_json(p_entry);
  if v_user is null then raise exception 'authentication required' using errcode='28000'; end if;
  if not public.can_edit_site(p_site_id) then raise exception 'forbidden' using errcode='42501'; end if;
  v_id := (p_entry->>'id')::uuid;
  v_kind := p_entry->>'kind'; v_parent := nullif(p_entry->>'parent_id','')::uuid;
  v_name := p_entry->>'normalized_name'; v_status := p_entry->>'status';
  v_payload := p_entry->'payload'; v_deleted := coalesce((p_entry->>'deleted')::boolean,false);
  v_learning_key := nullif(p_entry->>'learning_key','');
  v_delta_usage := coalesce((p_entry->'learning_delta'->>'usage')::integer,0);
  v_delta_finalized := coalesce((p_entry->'learning_delta'->>'finalized')::integer,0);
  v_usage := (p_entry->>'usage_count')::integer; v_finalized := (p_entry->>'finalized_usage_count')::integer;
  if v_id is null or v_kind not in ('site','trade','vendor','task','location','material-type','material-item','template')
    or v_name is null or v_name='' or v_status not in ('candidate','confirmed')
    or jsonb_typeof(v_payload)<>'object' or v_payload->>'id'<>v_id::text
    or v_usage<0 or v_finalized<0 or v_finalized>v_usage
    or p_base_revision<0 or length(coalesce(v_learning_key,''))>128
    or v_delta_usage<0 or v_delta_finalized<0 or v_delta_finalized>v_delta_usage
    or (v_learning_key is null and p_entry ? 'learning_delta')
    then raise exception 'invalid memory entry' using errcode='22023'; end if;
  if v_name is distinct from (case when v_kind='material-item' then coalesce(v_payload->>'fieldType','')||':'||coalesce(v_payload->>'normalizedValue','')
    else v_payload->>'normalizedName' end)
    or (v_kind<>'template' and coalesce(v_payload->>'status','confirmed')<>v_status)
    or (v_kind in ('vendor','task') and nullif(v_payload->>'tradeTypeId','')::uuid is distinct from v_parent)
    or (v_kind='material-item' and nullif(v_payload->>'materialTypeId','')::uuid is distinct from v_parent)
    then raise exception 'memory entry fields mismatch' using errcode='22023'; end if;
  if (v_kind in ('vendor','task','material-item')) <> (v_parent is not null) then
    raise exception 'invalid memory parent' using errcode='22023'; end if;
  if v_learning_key is null or v_learning_key not like 'apply:%' or v_delta_usage <> 1 or v_delta_finalized <> 0 or v_deleted then
    raise exception 'invalid application event' using errcode='22023';
  end if;
  -- Serialize same-site identity resolution, event deduplication and increments.
  perform pg_advisory_xact_lock(hashtextextended('memory-application:' || p_site_id::text, 0));
  v_hash := encode(digest(concat_ws('|',p_site_id::text,p_base_revision::text,p_entry::text),'sha256'),'hex');
  select * into v_prior from public.sync_operations where site_id=p_site_id and user_id=v_user and mutation_id=p_mutation_id;
  if found then
    if v_prior.request_hash<>v_hash then raise exception 'mutation id reused with different payload' using errcode='22023'; end if;
    return v_prior.result || jsonb_build_object('replayed',true);
  end if;
  select * into v_current from public.memory_entries where id=v_id and site_id=p_site_id for update;
  if v_current.id is null then
    select * into v_current from public.memory_entries where site_id=p_site_id and kind=v_kind
      and parent_id is not distinct from v_parent and normalized_name=v_name and deleted_at is null for update;
    if found then v_id := v_current.id; end if;
  end if;
  if v_learning_key is not null and exists(select 1 from public.memory_learning_events
    where site_id=p_site_id and entry_id=v_id and learning_key=v_learning_key) then
    select revision into v_revision from public.memory_entries where id=v_id and site_id=p_site_id;
    v_result:=jsonb_build_object('status','duplicate','entity_id',v_id,'revision',v_revision);
    insert into public.sync_operations(site_id,user_id,mutation_id,request_hash,result)
      values(p_site_id,v_user,p_mutation_id,v_hash,v_result);
    return v_result;
  end if;
  if v_parent is not null and not exists(
    select 1 from public.memory_entries where id=v_parent and site_id=p_site_id and deleted_at is null
      and kind=case when v_kind='material-item' then 'material-type' else 'trade' end
  ) then raise exception 'memory parent missing' using errcode='23503'; end if;
  if v_current.id is not null then
    if v_current.deleted_at is not null and v_learning_key is not null then
      v_result:=jsonb_build_object('status','conflict','entity_id',v_id,'revision',v_current.revision,'remote_payload',to_jsonb(v_current));
    elsif v_learning_key is not null then
      v_usage := v_current.usage_count+v_delta_usage;
      v_finalized := v_current.finalized_usage_count+v_delta_finalized;
      v_status := case when v_current.status='confirmed' or v_usage>=4 then 'confirmed' else 'candidate' end;
      v_payload := v_current.payload || jsonb_build_object('usageCount',v_usage,'finalizedUsageCount',v_finalized,
        'status',v_status,'lastUsedAt',greatest(coalesce(v_current.payload->>'lastUsedAt',''),coalesce(v_payload->>'lastUsedAt','')));
      update public.memory_entries set payload=v_payload,status=v_status,usage_count=v_usage,finalized_usage_count=v_finalized,
        revision=revision+1,updated_by=v_user,updated_at=now() where id=v_id returning revision into v_revision;
    elsif v_current.revision<>p_base_revision then
      v_result:=jsonb_build_object('status','conflict','entity_id',v_id,'revision',v_current.revision,'remote_payload',to_jsonb(v_current));
    else
      update public.memory_entries set kind=v_kind,parent_id=v_parent,normalized_name=v_name,payload=v_payload,status=v_status,
        usage_count=v_usage,finalized_usage_count=v_finalized,revision=revision+1,updated_by=v_user,updated_at=now(),
        deleted_at=case when v_deleted then now() else null end where id=v_id returning revision into v_revision;
    end if;
  elsif p_base_revision<>0 then
    v_result:=jsonb_build_object('status','conflict','entity_id',v_id,'revision',0,'remote_payload',null);
  else
    begin
      v_usage := 1; v_finalized := 0; v_status := 'candidate';
      v_payload := v_payload || jsonb_build_object('id',v_id,'usageCount',1,'finalizedUsageCount',0,'status','candidate');
      insert into public.memory_entries(id,site_id,kind,parent_id,normalized_name,payload,status,usage_count,finalized_usage_count,updated_by,deleted_at)
        values(v_id,p_site_id,v_kind,v_parent,v_name,v_payload,v_status,v_usage,v_finalized,v_user,case when v_deleted then now() else null end)
        returning revision into v_revision;
    exception when unique_violation then
      raise exception 'concurrent memory creation; retry application' using errcode='40001';
    end;
  end if;
  if v_result is null then
    if v_learning_key is not null then
      insert into public.memory_learning_events(site_id,entry_id,learning_key) values(p_site_id,v_id,v_learning_key);
    end if;
    insert into public.site_sync_state(site_id,last_sequence) values(p_site_id,0) on conflict(site_id) do nothing;
    update public.site_sync_state set last_sequence=last_sequence+1 where site_id=p_site_id returning last_sequence into v_sequence;
    insert into public.site_changes(site_id,sequence,entity,entity_id,operation,revision)
      values(p_site_id,v_sequence,'memory-entry',v_id,case when v_deleted then 'delete' else 'upsert' end,v_revision);
    v_result:=jsonb_build_object('status','applied','entity_id',v_id,'revision',v_revision,'sequence',v_sequence);
  end if;
  insert into public.sync_operations(site_id,user_id,mutation_id,request_hash,result)
    values(p_site_id,v_user,p_mutation_id,v_hash,v_result);
  return v_result;
end $$;

create or replace function public.approve_site_member(p_request_id uuid, p_role text default 'editor')
returns uuid language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_request public.join_requests;
begin
  if p_role not in ('editor', 'viewer') then raise exception 'invalid member role' using errcode = '22023'; end if;
  select * into v_request from public.join_requests where id = p_request_id;
  if v_request.id is null then raise exception 'forbidden' using errcode='42501'; end if;
  if auth.uid() is null or not public.can_manage_site(v_request.site_id) then raise exception 'forbidden' using errcode='42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended('audit-site:' || v_request.site_id::text, 0));
  select * into v_request from public.join_requests where id = p_request_id for update;
  if v_request.id is null or not public.can_manage_site(v_request.site_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  if v_request.status <> 'pending' then return v_request.user_id; end if;
  insert into public.site_members(site_id, user_id, role) values (v_request.site_id, v_request.user_id, p_role)
    on conflict (site_id, user_id) do nothing;
  update public.join_requests set status = 'approved', resolved_at = now(), resolved_by = auth.uid() where id = p_request_id;
  return v_request.user_id;
end $$;

create or replace function public.reject_site_join_request(p_request_id uuid)
returns uuid language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_request public.join_requests;
begin
  select * into v_request from public.join_requests where id = p_request_id;
  if v_request.id is null then raise exception 'forbidden' using errcode='42501'; end if;
  if auth.uid() is null or not public.can_manage_site(v_request.site_id) then raise exception 'forbidden' using errcode='42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended('audit-site:' || v_request.site_id::text, 0));
  select * into v_request from public.join_requests where id = p_request_id for update;
  if v_request.id is null or not public.can_manage_site(v_request.site_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  if v_request.status <> 'pending' then return v_request.user_id; end if;
  update public.join_requests set status = 'rejected', resolved_at = now(), resolved_by = auth.uid() where id = p_request_id;
  return v_request.user_id;
end $$;

create or replace function public.update_site_member_role(p_site_id uuid, p_user_id uuid, p_role text)
returns void language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_current text; v_owner_count integer;
begin
  if auth.uid() is null or not public.can_manage_site(p_site_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended('audit-site:' || p_site_id::text, 0));
  if not public.can_manage_site(p_site_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  if p_role not in ('owner', 'editor', 'viewer') then raise exception 'invalid member role' using errcode = '22023'; end if;
  select role into v_current from public.site_members where site_id = p_site_id and user_id = p_user_id for update;
  if v_current is null then raise exception 'member not found' using errcode = 'P0002'; end if;
  if v_current = 'owner' and p_role <> 'owner' then
    select count(*) into v_owner_count from public.site_members where site_id = p_site_id and role = 'owner';
    if v_owner_count <= 1 then raise exception 'cannot demote last owner' using errcode = '23514'; end if;
  end if;
  update public.site_members set role = p_role where site_id = p_site_id and user_id = p_user_id;
end $$;

create or replace function public.remove_site_member(p_site_id uuid, p_user_id uuid)
returns void language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_role text; v_owner_count integer;
begin
  if auth.uid() is null or (not public.can_manage_site(p_site_id) and auth.uid() <> p_user_id) then raise exception 'forbidden' using errcode = '42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended('audit-site:' || p_site_id::text, 0));
  if not public.can_manage_site(p_site_id) and auth.uid() <> p_user_id then raise exception 'forbidden' using errcode = '42501'; end if;
  select role into v_role from public.site_members where site_id = p_site_id and user_id = p_user_id for update;
  if v_role is null then return; end if;
  if v_role = 'owner' then
    select count(*) into v_owner_count from public.site_members where site_id = p_site_id and role = 'owner';
    if v_owner_count <= 1 then raise exception 'cannot remove last owner' using errcode = '23514'; end if;
  end if;
  delete from public.site_members where site_id = p_site_id and user_id = p_user_id;
end $$;


-- Included in the sync maintenance migration after audit hardening.
-- Read-only capability discovery, restricted to members of the requested site.
create or replace function public.get_sync_capabilities(p_site_id uuid)
returns jsonb language plpgsql stable security invoker
set search_path = public, pg_temp
as $$
declare v_capabilities jsonb; v_can_edit boolean;
begin
  if auth.uid() is null or not public.is_site_member(p_site_id) then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  v_can_edit := public.can_edit_site(p_site_id);
  select coalesce(jsonb_agg(name order by name), '[]'::jsonb) into v_capabilities
  from (values
    ('apply_memory_application', 'public.apply_memory_application(uuid,uuid,bigint,jsonb)', array['p_site_id','p_mutation_id','p_base_revision','p_entry']),
    ('apply_memory_entry_mutation', 'public.apply_memory_entry_mutation(uuid,uuid,bigint,jsonb)', array['p_site_id','p_mutation_id','p_base_revision','p_entry']),
    ('apply_daily_draft_mutation', 'public.apply_daily_draft_mutation(uuid,uuid,uuid,bigint,jsonb)', array['p_site_id','p_mutation_id','p_entity_id','p_base_revision','p_payload']),
    ('apply_daily_field_mutation', 'public.apply_daily_field_mutation(uuid,uuid,uuid,date,jsonb)', array['p_site_id','p_mutation_id','p_entity_id','p_report_date','p_changes']),
    ('apply_water_field_mutation', 'public.apply_water_field_mutation(uuid,uuid,jsonb)', array['p_site_id','p_mutation_id','p_changes']),
    ('apply_water_snapshot_mutation', 'public.apply_water_snapshot_mutation(uuid,uuid,bigint,jsonb)', array['p_site_id','p_mutation_id','p_base_revision','p_payload'])
  ) as required(name, signature, arguments)
  join pg_proc p on p.oid = to_regprocedure(signature)
  where v_can_edit and p.proargnames = arguments::text[] and has_function_privilege(current_user, p.oid, 'EXECUTE');
  return jsonb_build_object('contract_version', 1, 'capabilities', v_capabilities);
end;
$$;
revoke all on function public.get_sync_capabilities(uuid) from public, anon;
grant execute on function public.get_sync_capabilities(uuid) to authenticated;
notify pgrst, 'reload schema';

commit;
