import type { AuthSnapshot } from '../auth/auth-service';
import type { SiteSummary } from '../domain/shared';
import type { JoinRequestSummary, SiteMemberSummary } from '../data/remote/site-repository';
import type { SyncOperation } from '../sync/types';
import type { ConflictReview } from '../sync/conflict-review';
import type { MemoryImportPreview } from '../sync/memory-import';

export interface AccountPageState {
  auth: AuthSnapshot;
  sites: SiteSummary[];
  activeSiteId: string | null;
  pendingCount: number;
  requests: JoinRequestSummary[];
  members: SiteMemberSummary[];
  feedback: string;
  error: string;
  diagnostics?: SyncOperation[];
  operations?: SyncOperation[];
  operationsStatus?: 'loading' | 'ready' | 'error';
  conflicts?: ConflictReview[];
  importPreview?: MemoryImportPreview | null;
}

const escapeHtml = (value: string): string => value.replace(/[&<>']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;' }[char]!));
const roleLabel = (role: SiteSummary['role']): string => role === 'owner' ? '管理員' : role === 'editor' ? '編輯者' : '檢視者';

export function renderAccountPage(state: AccountPageState): string {
  if (!state.auth.enabled) return `<section class="account-content"><section class="form-card account-status"><strong>目前使用本機模式</strong><p>資料只存在這台裝置。部署時設定 Supabase URL 與 publishable key 後，才會啟用登入和跨裝置共用；既有資料不會自動上傳。</p></section>${state.error ? `<p class="issues" role="alert">${escapeHtml(state.error)} <button type="button" data-account-action="retry-load-account">重新讀取</button></p>` : ''}</section>`;
  if (!state.auth.user) return `<section class="account-content"><section class="form-card account-status"><strong>登入後才能使用共用工地</strong><p>每位成員使用自己的帳號；登入成功後仍需建立工地或經管理員核准加入。</p><button type="button" class="primary" data-account-action="sign-in">使用 Google 登入</button></section>${state.error ? `<p class="issues" role="alert">${escapeHtml(state.error)} <button type="button" data-account-action="retry-load-account">重新讀取</button></p>` : ''}</section>`;
  const userLabel = state.auth.user.email ?? state.auth.user.id;
  const siteRows = state.sites.map((site) => `<article class="account-site${site.id === state.activeSiteId ? ' active' : ''}"><div class="account-site__details"><div class="account-site__primary"><strong>${escapeHtml(site.name)}</strong><div class="account-join-code"><span>加入碼</span><code>${escapeHtml(site.joinCode)}</code><button type="button" aria-label="複製 ${escapeHtml(site.name)} 加入碼" data-account-action="copy-join-code" data-site-id="${site.id}">複製</button></div></div><small>${roleLabel(site.role)}${site.id === state.activeSiteId ? ' · 目前使用' : ''}</small></div><button type="button" data-account-action="select-site" data-site-id="${site.id}"${site.id === state.activeSiteId ? ' disabled' : ''}>${site.id === state.activeSiteId ? '使用中' : '切換'}</button></article>`).join('');
  const memberRow = (member: SiteMemberSummary) => { const mine = member.userId === state.auth.user?.id; return `<article class="account-member"><div><strong>${escapeHtml(mine ? `${member.userId}（你）` : member.userId)}</strong><small>${roleLabel(member.role)}</small></div><div><button type="button" class="account-role-button${member.role === 'viewer' ? ' active' : ''}" aria-pressed="${member.role === 'viewer'}" data-account-action="role-viewer" data-site-id="${member.siteId}" data-user-id="${member.userId}">檢視</button><button type="button" class="account-role-button${member.role === 'editor' ? ' active' : ''}" aria-pressed="${member.role === 'editor'}" data-account-action="role-editor" data-site-id="${member.siteId}" data-user-id="${member.userId}">編輯</button><button type="button" class="account-role-button${member.role === 'owner' ? ' active' : ''}" aria-pressed="${member.role === 'owner'}" data-account-action="role-owner" data-site-id="${member.siteId}" data-user-id="${member.userId}">管理員</button><button type="button" class="danger-text" data-account-action="remove-member" data-site-id="${member.siteId}" data-user-id="${member.userId}">移除</button></div></article>`; };
  const administration = state.sites.filter((site) => site.role === 'owner').map((site) => {
    const requestRows = state.requests.filter((request) => request.siteId === site.id).map((request) => `<article class="account-member"><div><strong>${escapeHtml(request.userId)}</strong><small>申請者</small></div><div><button type="button" data-account-action="reject-request" data-request-id="${request.id}">拒絕</button><button type="button" data-account-action="approve-viewer" data-request-id="${request.id}">核准檢視</button><button type="button" class="primary" data-account-action="approve-editor" data-request-id="${request.id}">核准編輯</button></div></article>`).join('');
    const memberRows = state.members.filter((member) => member.siteId === site.id).map(memberRow).join('');
    return `<section class="form-card account-administration"><h2>${escapeHtml(site.name)}</h2><section class="account-member-group"><h3>待審核申請</h3><div class="account-sites">${requestRows || '<p class="empty">目前沒有待審核申請。</p>'}</div></section><section class="account-member-group"><h3>現有成員</h3><div class="account-sites">${memberRows || '<p class="empty">目前沒有現有成員。</p>'}</div></section></section>`;
  }).join('');
  const type = (entity: SyncOperation['entity']) => entity.startsWith('daily') ? '施工日報' : entity.startsWith('water') ? '水位' : entity.startsWith('memory') ? '工地記憶' : entity;
  const operations = state.operations ?? [];
  const failures = (state.diagnostics ?? []).filter((row) => row.status === 'failed' || row.status === 'conflict' || row.status === 'blocked');
  const conflictCounts = failures.filter((row) => row.status === 'conflict').reduce((counts, row) => { const key = type(row.entity); counts[key] = (counts[key] ?? 0) + 1; return counts; }, {} as Record<string, number>);
  const missingRpc = failures.some((row) => row.status === 'blocked' && row.lastErrorCode === 'PGRST202');
  const diagnostics = failures.length ? `<section class="form-card account-sync-diagnostics"><h2>同步診斷</h2><p>這些是尚未成功的操作，資料仍安全保留在此裝置。${Object.keys(conflictCounts).length ? ` 剩餘衝突：${escapeHtml(Object.entries(conflictCounts).map(([key, count]) => `${key} ${count} 筆`).join('、'))}。` : ''}</p><ul>${failures.map((row) => { const date = row.entity === 'daily-patch' ? (row.payload as { reportDate?: string }).reportDate : row.entity === 'daily-draft' ? (row.payload as { date?: string }).date : undefined; return `<li><strong>${type(row.entity)}</strong><span>${row.status === 'conflict' ? '需要處理衝突' : row.status === 'blocked' ? '已停止重試' : `第 ${row.attempts} 次失敗，等待手動同步`}</span><small>${escapeHtml([date ? `日報日期 ${date}` : '', row.entity === 'daily-draft' ? '舊版整份日報' : row.entity === 'daily-patch' ? '欄位修改' : '', row.lastErrorCode, row.lastError, row.lastErrorHint].filter(Boolean).join('｜') || '雲端版本衝突，請重新同步後確認資料。')}</small></li>`; }).join('')}</ul>${missingRpc ? '<button type="button" class="primary" data-account-action="retry-missing-rpc">修復後重試</button>' : ''}</section>` : '';
  const reviews = state.conflicts ?? [];
  const kindLabel = (kind: ConflictReview['kind']) => kind === 'daily' ? '施工日報' : kind === 'water' ? '水位' : '主檔';
  const printable = (value: unknown) => escapeHtml(JSON.stringify(value));
  const conflictReview = reviews.length ? `<section class="form-card account-sync-diagnostics"><h2>衝突檢視與處理</h2><p>每一項先比較目前雲端版本與保留的本機原文；新操作成功寫入前，舊操作不會刪除。</p><div class="action-row"><button type="button" data-account-action="export-conflict-backups">下載處理前備份</button></div>${reviews.map((review) => `<details class="account-conflict-review"><summary><strong>${kindLabel(review.kind)}</strong>${review.reportDate ? `｜${escapeHtml(review.reportDate)}` : ''}｜${review.diffs.length} 項差異</summary><form data-conflict-review="${review.id}"><p class="hint">建立時間：${escapeHtml(new Date(review.createdAt).toLocaleString('zh-TW'))}</p>${review.diffs.map((diff) => `<article class="account-conflict-diff"><strong>${escapeHtml(diff.kind)}：${escapeHtml(diff.path)}</strong><small>本機：${printable(diff.local)}</small><small>雲端：${printable(diff.cloud)}</small><label>採用<select data-conflict-choice="${escapeHtml(diff.path)}"><option value="cloud">雲端</option><option value="local">本機</option></select></label></article>`).join('') || '<p class="empty">兩邊內容相同。</p>'}<details><summary>處理前原始內容</summary><pre>${printable({ local: review.local, cloud: review.cloud })}</pre></details><button type="button" class="primary" data-account-action="resolve-conflict" data-conflict-id="${review.id}">確認選擇並建立同步操作</button></form></details>`).join('')}</section>` : '';
  const conflictFallback = !reviews.length && failures.some((row) => row.status === 'conflict')
    ? '<section class="form-card account-sync-diagnostics"><h2>衝突明細尚未顯示</h2><p>本機仍保留衝突操作。下載備份後，可直接讀取這筆衝突的雲端版本。</p><div class="action-row"><button type="button" data-account-action="export-conflict-backups">下載處理前備份</button><button type="button" data-account-action="load-conflict-reviews">讀取衝突明細</button></div></section>'
    : '';
  const operationDate = (row: SyncOperation) => row.entity === 'daily-patch' ? (row.payload as { reportDate?: string }).reportDate : row.entity === 'daily-draft' ? (row.payload as { date?: string }).date : undefined;
  const operationFields = (row: SyncOperation) => row.entity.endsWith('-patch') ? [...new Set(((row.payload as { changes?: Array<{ collection: string; field?: string }> }).changes ?? []).map((change) => change.field ? `${change.collection}.${change.field}` : change.collection))].slice(0, 3).join('、') : row.entity === 'memory' ? '舊版主檔快照（保留備份）' : row.entity === 'memory-entry' ? `${(row.payload as { kind?: string }).kind ?? '記憶'}逐筆修改` : '整份快照';
  const statusLabel = (row: SyncOperation) => row.status === 'pending' ? '待同步' : row.status === 'sending' ? '同步中' : row.status === 'failed' ? '等待重試' : row.status === 'blocked' ? '已停止重試' : '需要處理衝突';
  const queue = state.operationsStatus === 'loading' ? '<section class="form-card account-sync-diagnostics"><h2>待同步項目</h2><p role="status">正在讀取本機同步佇列…</p></section>' : state.operationsStatus === 'error' ? '<section class="form-card account-sync-diagnostics"><h2>待同步項目</h2><p role="alert">本機同步佇列讀取失敗；資料未被清除，請重新讀取。</p></section>' : operations.length ? `<section class="form-card account-sync-diagnostics"><h2>待同步項目</h2><p>共 ${operations.length} 筆；此明細與頁首待同步數量相同，僅顯示安全摘要。</p><ul>${operations.map((row) => `<li><strong>${type(row.entity)}</strong><span>${statusLabel(row)}</span><small>${escapeHtml([operationDate(row) ? `日報日期 ${operationDate(row)}` : '', operationFields(row), `建立 ${new Date(row.createdAt).toLocaleString('zh-TW')}`, row.lastErrorCode, row.lastErrorHint ?? row.lastError].filter(Boolean).join('｜'))}</small></li>`).join('')}</ul></section>` : '<section class="form-card account-sync-diagnostics"><h2>待同步項目</h2><p class="empty">目前沒有待同步資料；這代表此工地的本機佇列沒有等待雲端確認的操作。</p></section>';
  const pendingLabel = state.operationsStatus === 'loading' ? '待同步讀取中' : state.operationsStatus === 'error' ? '待同步無法讀取' : `待同步 ${state.pendingCount} 筆`;
  const canImport = state.sites.some((site) => site.id === state.activeSiteId && site.role === 'owner');
  const preview = state.importPreview;
  const importPanel = canImport ? `<section class="form-card account-sync-diagnostics"><h2>匯入舊本機記憶</h2><p>先比對這台裝置的本機記憶與目前工地；原始資料與既有雲端快照保留。</p><button type="button" data-account-action="preview-memory-import">預覽匯入</button>${operations.some((row) => row.entity === 'memory') ? '<button type="button" data-account-action="preview-legacy-memory-import">預覽舊版待送快照</button>' : ''}${preview ? `<p>新增 ${preview.add.length} 筆、相同 ${preview.duplicate.length} 筆、衝突 ${preview.conflict.length} 筆。</p>${preview.add.length ? `<details><summary>將新增的記憶</summary><ul>${preview.add.map((entry) => `<li>${escapeHtml(entry.kind)}：${escapeHtml(String(entry.payload.name ?? entry.payload.value ?? entry.payload.text ?? entry.normalized_name))}</li>`).join('')}</ul></details>` : ''}${preview.conflict.length ? `<details><summary>衝突（預設略過，可逐筆採用本機內容）</summary><ul>${preview.conflict.map((entry) => `<li><label><input type="checkbox" data-memory-import-conflict value="${escapeHtml(entry.id)}"${entry.base_revision === undefined ? ' disabled' : ''}>${escapeHtml(entry.kind)}：${escapeHtml(String(entry.payload.name ?? entry.payload.value ?? entry.payload.text ?? entry.normalized_name))}</label></li>`).join('')}</ul></details>` : ''}<button type="button" class="primary" data-account-action="confirm-memory-import">確認匯入所選項</button>` : ''}</section>` : '';
  return `<section class="account-content"><section class="form-card account-identity"><div><span>登入帳號</span><strong>${escapeHtml(userLabel)}</strong></div><button type="button" data-account-action="sign-out">登出</button></section>${state.feedback ? `<p class="account-feedback" role="status">${escapeHtml(state.feedback)}</p>` : ''}${state.error ? `<p class="issues" role="alert">${escapeHtml(state.error)} <button type="button" data-account-action="retry-load-account">重新讀取</button></p>` : ''}<section class="form-card account-site-panel"><div class="account-sites__header"><div><h2>我的工地</h2><small>${state.activeSiteId ? `目前使用中 · ${pendingLabel}` : '請先選擇工地'}</small></div></div><div class="account-sites">${siteRows || '<p class="empty">目前還沒有可使用的工地。</p>'}</div></section>${importPanel}${queue}${diagnostics}${conflictReview}${conflictFallback}<section class="account-actions"><form class="form-card" data-account-form="create-site"><h2>建立工地</h2><label>工地名稱<input name="name" maxlength="100" required autocomplete="organization"></label><button type="submit" class="primary">建立並成為管理員</button></form><form class="form-card" data-account-form="request-join"><h2>申請加入工地</h2><label>加入碼<input name="joinCode" maxlength="32" required autocapitalize="none" autocomplete="off"></label><button type="submit">送出申請</button></form></section>${administration}</section>`;
}
