import type { AccountPageState } from './account-view';
import type { SyncOperation } from '../sync/types';
import type { ConflictReview } from '../sync/conflict-review';
import { escapeHtml } from '../shared/html';
import { renderMemoryConflictChoice } from './memory-conflict-view';

export function renderSyncDiagnosticsPage(state: AccountPageState): string {
  if (!state.auth.enabled) return '<section class="form-card account-status"><strong>目前使用本機模式</strong><p>雲端同步未啟用；仍可查看下方本機偵錯資訊。</p></section>';
  if (!state.auth.user) return '<section class="form-card account-status"><strong>登入後才能診斷共用工地同步</strong><p><a href="#settings/account">前往共用工地登入</a></p></section>';
  const activeSite = state.sites.find((site) => site.id === state.activeSiteId);
  if (!activeSite) return '<section class="form-card account-status"><strong>請先選擇要診斷的工地</strong><p><a href="#settings/account">前往共用工地選擇或加入工地</a></p></section>';
  const pendingLabel = state.operationsStatus === 'loading' ? '待同步讀取中' : state.operationsStatus === 'error' ? '待同步無法讀取' : `待同步 ${state.pendingCount} 筆`;
  const context = `<section class="form-card account-sync-context" aria-label="目前診斷工地"><h2>${escapeHtml(activeSite.name)}</h2><p>${pendingLabel}</p><div class="action-row"><button type="button" class="primary" data-account-action="sync-now"${state.syncing ? ' disabled' : ''}>${state.syncing ? '同步中…' : '立即同步'}</button><a href="#settings/account">切換或管理工地</a></div></section>`;
  const type = (entity: SyncOperation['entity']) => entity.startsWith('daily') ? '施工日報' : entity.startsWith('water') ? '水位' : entity.startsWith('memory') ? '工地記憶' : entity;
  const operations = state.operations ?? [];
  const failures = (state.diagnostics ?? []).filter((row) => row.status === 'failed' || row.status === 'conflict' || row.status === 'blocked');
  const conflictCounts = failures.filter((row) => row.status === 'conflict').reduce((counts, row) => { const key = type(row.entity); counts[key] = (counts[key] ?? 0) + 1; return counts; }, {} as Record<string, number>);
  const missingRpc = failures.some((row) => row.status === 'blocked' && ['PGRST202', '42883'].includes(row.lastErrorCode ?? ''));
  const errorSummary = (row: SyncOperation): string => row.lastErrorCode === '23505' ? '雲端已有同名記憶，等待同步修復接管雲端版本。' : row.lastErrorCode === '23503' ? '子項目正在等待父層工種完成，等待同步修復重新綁定。' : [row.lastErrorCode, row.lastError, row.lastErrorHint].filter(Boolean).join('｜') || '雲端版本衝突，請重新同步後確認資料。';
  const diagnostics = failures.length ? `<section class="form-card account-sync-diagnostics"><h2>同步診斷</h2><p>這些是尚未成功的操作，資料仍安全保留在此裝置。${Object.keys(conflictCounts).length ? ` 剩餘衝突：${escapeHtml(Object.entries(conflictCounts).map(([key, count]) => `${key} ${count} 筆`).join('、'))}。` : ''}</p><ul>${failures.map((row) => { const date = row.entity === 'daily-patch' ? (row.payload as { reportDate?: string }).reportDate : row.entity === 'daily-draft' ? (row.payload as { date?: string }).date : undefined; return `<li><strong>${type(row.entity)}</strong><span>${row.status === 'conflict' ? '需要處理衝突' : row.status === 'blocked' ? '已停止重試' : `第 ${row.attempts} 次失敗，等待手動同步`}</span><small>${escapeHtml([date ? `日報日期 ${date}` : '', row.entity === 'daily-draft' ? '舊版整份日報' : row.entity === 'daily-patch' ? '欄位修改' : '', errorSummary(row)].filter(Boolean).join('｜'))}</small></li>`; }).join('')}</ul>${missingRpc ? '<button type="button" class="primary" data-account-action="retry-missing-rpc">檢查並安全重試</button>' : ''}</section>` : '';
  const reviews = state.conflicts ?? [];
  const kindLabel = (kind: ConflictReview['kind']) => kind === 'daily' ? '施工日報' : kind === 'water' ? '水位' : '主檔';
  const printable = (value: unknown) => escapeHtml(value === undefined ? '（不存在）' : JSON.stringify(value));
  const conflictReview = reviews.length ? `<section class="form-card account-sync-diagnostics"><h2>衝突檢視與處理</h2><p>每一項先比較目前雲端版本與保留的本機原文；新操作成功寫入前，舊操作不會刪除。</p><div class="action-row"><button type="button" data-account-action="export-conflict-backups">下載處理前備份</button></div>${reviews.map((review) => `<details class="account-conflict-review"><summary><strong>${kindLabel(review.kind)}</strong>${review.reportDate ? `｜${escapeHtml(review.reportDate)}` : ''}｜${review.diffs.length} 項差異</summary><form data-conflict-review="${escapeHtml(review.id)}"><p class="hint">建立時間：${escapeHtml(new Date(review.createdAt).toLocaleString('zh-TW'))}</p>${review.entity === 'memory-entry' ? renderMemoryConflictChoice(review, escapeHtml) : review.diffs.map((diff) => `<article class="account-conflict-diff"><strong>${escapeHtml(diff.kind)}：${escapeHtml(diff.path)}</strong><small>本機：${printable(diff.local)}</small><small>雲端：${printable(diff.cloud)}</small><label>採用<select data-conflict-choice="${escapeHtml(diff.path)}"><option value="cloud">雲端</option><option value="local">本機</option></select></label></article>`).join('') || '<p class="empty">兩邊內容相同。</p>'}<details><summary>處理前原始內容</summary><pre>${printable({ local: review.local, cloud: review.cloud })}</pre></details><button type="button" class="primary" data-account-action="resolve-conflict" data-conflict-id="${escapeHtml(review.id)}">確認選擇並建立同步操作</button></form></details>`).join('')}</section>` : '';
  const conflictFallback = !reviews.length && failures.some((row) => row.status === 'conflict')
    ? '<section class="form-card account-sync-diagnostics"><h2>衝突明細尚未顯示</h2><p>本機仍保留衝突操作。下載備份後，可直接讀取這筆衝突的雲端版本。</p><div class="action-row"><button type="button" data-account-action="export-conflict-backups">下載處理前備份</button><button type="button" data-account-action="load-conflict-reviews">讀取衝突明細</button></div></section>'
    : '';
  const operationDate = (row: SyncOperation) => row.entity === 'daily-patch' ? (row.payload as { reportDate?: string }).reportDate : row.entity === 'daily-draft' ? (row.payload as { date?: string }).date : undefined;
  const operationFields = (row: SyncOperation) => row.entity.endsWith('-patch') ? [...new Set(((row.payload as { changes?: Array<{ collection: string; field?: string }> }).changes ?? []).map((change) => change.field ? `${change.collection}.${change.field}` : change.collection))].slice(0, 3).join('、') : row.entity === 'memory' ? '舊版主檔快照（保留備份）' : row.entity === 'memory-entry' ? `${(row.payload as { kind?: string }).kind ?? '記憶'}逐筆修改` : '整份快照';
  const statusLabel = (row: SyncOperation) => row.status === 'pending' ? '待同步' : row.status === 'sending' ? '同步中' : row.status === 'failed' ? '等待重試' : row.status === 'blocked' ? '已停止重試' : '需要處理衝突';
  const queue = state.operationsStatus === 'loading' ? '<section class="form-card account-sync-diagnostics"><h2>待同步項目</h2><p role="status">正在讀取本機同步佇列…</p></section>' : state.operationsStatus === 'error' ? '<section class="form-card account-sync-diagnostics"><h2>待同步項目</h2><p role="alert">本機同步佇列讀取失敗；資料未被清除，請重新讀取。</p></section>' : operations.length ? `<section class="form-card account-sync-diagnostics"><h2>待同步項目</h2><p>共 ${operations.length} 筆；此明細與頁首待同步數量相同，僅顯示安全摘要。</p><ul>${operations.map((row) => `<li><strong>${type(row.entity)}</strong><span>${statusLabel(row)}</span><small>${escapeHtml([operationDate(row) ? `日報日期 ${operationDate(row)}` : '', operationFields(row), `建立 ${new Date(row.createdAt).toLocaleString('zh-TW')}`, row.lastErrorCode || row.lastError ? errorSummary(row) : ''].filter(Boolean).join('｜'))}</small></li>`).join('')}</ul></section>` : '<section class="form-card account-sync-diagnostics"><h2>待同步項目</h2><p class="empty">目前沒有待同步資料；這代表此工地的本機佇列沒有等待雲端確認的操作。</p></section>';
  const canImport = state.sites.some((site) => site.id === state.activeSiteId && site.role === 'owner');
  const preview = state.importPreview;
  const importBusy = operations.some((row) => row.entity === 'memory' || (row.entity === 'memory-entry' && ['pending', 'sending', 'blocked'].includes(row.status)));
  const importPanel = canImport ? `<section class="form-card account-sync-diagnostics"><h2>匯入舊本機記憶</h2><p>先比對這台裝置的本機記憶與目前工地；原始資料與既有雲端快照保留。</p><button type="button" data-account-action="preview-memory-import"${importBusy ? ' disabled' : ''}>預覽匯入</button>${operations.some((row) => row.entity === 'memory') ? '<button type="button" data-account-action="preview-legacy-memory-import">預覽舊版待送快照</button>' : ''}${importBusy ? '<p class="hint">請先完成同步修復或目前的記憶匯入，避免重複排入。</p>' : ''}${preview ? `<p>新增 ${preview.add.length} 筆、相同 ${preview.duplicate.length} 筆、衝突 ${preview.conflict.length} 筆。</p>${preview.add.length ? `<details><summary>將新增的記憶</summary><ul>${preview.add.map((entry) => `<li>${escapeHtml(entry.kind)}：${escapeHtml(String(entry.payload.name ?? entry.payload.value ?? entry.payload.text ?? entry.normalized_name))}</li>`).join('')}</ul></details>` : ''}${preview.conflict.length ? `<details><summary>衝突（預設略過，可逐筆採用本機內容）</summary><ul>${preview.conflict.map((entry) => `<li><label><input type="checkbox" data-memory-import-conflict value="${escapeHtml(entry.id)}"${entry.base_revision === undefined ? ' disabled' : ''}>${escapeHtml(entry.kind)}：${escapeHtml(String(entry.payload.name ?? entry.payload.value ?? entry.payload.text ?? entry.normalized_name))}</label></li>`).join('')}</ul></details>` : ''}<button type="button" class="primary" data-account-action="confirm-memory-import">確認匯入所選項</button>` : ''}</section>` : '';
  const recovery = state.recoveryPreview;
  const recoveryPanel = state.activeSiteId ? `<section class="form-card account-sync-diagnostics"><h2>修復舊同步項目</h2><p>此工具固定顯示。先預覽並下載備份；舊日報與水位採雲端優先，同名記憶採用已同步的雲端版本。</p>${canImport ? `<div class="action-row"><button type="button" data-account-action="preview-sync-recovery">預覽修復</button><button type="button" data-account-action="export-sync-recovery-backup"${recovery ? '' : ' disabled'}>下載處理前備份</button></div>` : '<p class="hint">目前帳號不是此工地管理員，僅能查看同步診斷。</p>'}${recovery ? `<p>將封存：日報 ${recovery.legacyDaily}、水位 ${recovery.legacyWater}、舊記憶快照 ${recovery.legacyMemory}、記憶錯誤 ${recovery.memoryProblems}；採用雲端記憶 ${recovery.cloudMemoryMatches}；重新排送 ${recovery.memoryToResend}；仍需人工處理 ${recovery.remainingManual}。</p><button type="button" class="primary" data-account-action="apply-sync-recovery">確認修復</button>` : ''}</section>` : '';

  return `${context}<section class="account-content" aria-label="同步問題處理"><p class="hint">處理順序：立即同步 → 比較衝突並下載備份 → 確認選擇後再次同步。</p>${queue}${diagnostics}${conflictReview}${conflictFallback}${recoveryPanel}${importPanel}</section>`;
}
